### PR TITLE
Translate screenshots in FR

### PR DESCRIPTION
**Pull request by jujudusud**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

Adding screenshots from 3.8.0 in FR
Refering to issue #413

### CODE REVIEW

**Comment by jujudusud** [comment]
Missing diagrams translated.

**Comment by gilgongo** [comment]
I've realised there are some UI-related changes to be made in the English version of Software-Manual.md that I forgot about when we made the translation branch. I guess these will have to come in later...

**Comment by gilgongo** [comment]
Hm. I think you may need to look at this: https://github.com/jamulussoftware/jamuluswebsite/pull/465 I've removed quite a few images as I thought they might be hard to maintain in the future and weren't really that useful. Some names have also had to change (now that there's three settings tabs, for instance).

**Comment by jujudusud** [comment]
After looking at #465, I will update this PR and made it ready for review.

**Pull request merged**
