### PR TITLE
UI menus re-arranged

### PR DESCRIPTION
**Pull request by jp8**
# Does this need translation?

- [x] Yes 
- [ ] No 

# Changes

Menubar has has menu as items re-arranged recently.
On jamulus project, see pull request #1926

### CODE REVIEW

**Comment by ann0see** [comment]
Needs to go to next-release...

**Comment by ann0see** [comment]
Thank you. Will be merged once we start the release cycle probably?

**Review by ann0see — CHANGES_REQUESTED** [review]
@jp8 could you please rebase this PR to the current next-release branch?

**Comment by jp8** [comment]
> @jp8 could you please rebase this PR to the current next-release branch?

git rebase next-release

gives me a lot of conflicts somehow.

Is there something i can give it to help it along ?  Or I could just close this and make a new pull request that starts from next-release.

**Comment by ann0see** [comment]
You could 
git checkout next-release 
git cherry-pick your commit (I hope this works) and then force push HEAD to the branch you want to merge into next-release.

If that doesn’t work, just open a new PR

**Comment by jp8** [comment]
Someday I may figure out how to cherry-pick and force push...  for now I have made a new pull request #587

**Comment by ann0see** [comment]
git checkout release 
git cherry-pick <commit>

Or git rebase release git rebase -i

**Pull request closed without merging**
