### PR TITLE
[ImgBot] Optimize images (#492)

### PR DESCRIPTION
**Pull request by ann0see**
*Total -- 5,163.94kb -> 2,701.63kb (47.68%)

# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

### CODE REVIEW

**Comment by ann0see** [comment]
Reminder to sync release back to translate and changes!

**Comment by gilgongo** [comment]
These are the deleted/updated images I think. I don't know how to do a manual merge though.

**Comment by ann0see** [comment]
Yes probably. I will try to resolve it manually later

**Comment by jujudusud** [comment]
Why do you merge images in release into changes ?
Images in changes have been deleted to be in Sync with 3.8.0 website version. Other ones have been updated with the new interface.

**Comment by ann0see** [comment]
Thanks for bringing this up. Is it ok now?

**Comment by ann0see** [comment]
I didn’t look close enough 😔

**Comment by jujudusud** [comment]
Will have a look. As soon as possible.

**Pull request merged**
