### PR TITLE
Optimise GH action 

### PR DESCRIPTION
**Pull request by ignotus666**
# Does this need translation?

- [ ] Yes 
- [ *] No 

# Changes

**NOTE**: this PR is superseded by #590 - it can be merged before that one, or ignored and merge #590 directly.

Changed jekyll.yml script so it just builds, zips and uploads the site on pull request, and does not run at all if not necessary (when merging changes other than those to EN .md files).

Also updated some variable names and comments so they are clearer to understand.

### CODE REVIEW

**Comment by ann0see** [comment]
Ok. This looks really easy ;-). I probably need to think a little bit more about it (or have someone else verify it too, especially concerning the logic).

**Comment by ignotus666** [comment]
I'm quite sure I tested all the scenarios in the table in #586 and it behaves following that - but yes, it would be good if someone else could check it out (aside from me, that is).

**Comment by ignotus666** [comment]
I added a document explaining how the whole po4a setup works. Hopefully it can help others understand what's going on and serve as a reference (for myself included) in future.

**Review by ann0see — COMMENTED** [review]
Looks good.

However, I‘d like to request a review from @gilgongo concerning the maintenance workflow and @pljones concerning the coding.

**Comment by gilgongo** [comment]
I think in so far as the English is still maintained in the .md files, the primary maintaince of the text of the site (if you edit it locally after a git clone, for exampe) in the "next release" branch is unaffected, and you need nothing more than git and (optionally) jekyll installed locally, is that right? 

Re. po4a-Setup-Explained.md, are the scripts now in GH actions or is it referring to local execution?

**Comment by ignotus666** [comment]
> is that right?

I'd say so.

> Re. po4a-Setup-Explained.md, are the scripts now in GH actions or is it referring to local execution?

It's all in GH actions. That doc explains how it all works under the hood.

**Comment by ann0see** [comment]
Kind of. You‘d need to download the .zip file which is being produced by the PR to actually see the whole page. Building with Jekyll locally is now a bit more complicated since you‘d need to install and run po4a scripts first. They‘d then generate the md files for other languages.

**Pull request merged**
