### PR TITLE
Remove obsolete .po files

### PR DESCRIPTION
**Pull request by ignotus666**
**Short description of changes**
Removes .po files that no longer have an EN counterpart. Their content is already in the translation memory on Weblate so won't get lost (in case it's been moved to other files).

**Context: Fixes an issue? Related issues**

**Status of this Pull Request**

**What is missing until this pull request can be merged?**

**Does this need translation?**

No.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Comment by jujudusud** [comment]
Footer is in use : #798

**Comment by ignotus666** [comment]
Yes, but that text has moved to another file, it's no longer in a separate 'footertext' doc.

**Review by ann0see — APPROVED** [review]
I think it's ok to remove these files. @gilgongo should verify that he removed these files fully and then merge this PR.

**Comment by ann0see** [comment]
Merged as I think it's ok. We can always revert it.

**Pull request merged**
