### PR TITLE
RELEASE: 3.10.0 (WEBSITE)

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Release PR for r 3.10.0. Ready for local testing. This is a WIP

**Context: Fixes an issue? Related issues**
Releated to release issue: https://github.com/jamulussoftware/jamulus/issues/3094

**Status of this Pull Request**

Ready for review.

**What is missing until this pull request can be merged?**

### CODE REVIEW

**Comment by ann0see** [comment]
Linkcheck errors:

```
http://localhost:4000/de/wiki/Client-Troubleshooting
- (261:101) 'ASIO4ALL..' => http://localhost:4000/de/wiki/Installation-for-Windows#setting-up-asio4all (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Getting-Started
- (237:0) 'FAQ' => http://localhost:4000/de/wiki/FAQ#warum-sollte-ich-keine-drahtlosen-ger%C3%A4te-verwenden (HTTP 200 but missing anchor)
- (239:4) 'FAQ' => http://localhost:4000/de/wiki/FAQ#warum-sollte-ich-keine-drahtlosen-ger%C3%A4te-verwenden (HTTP 200 but missing anchor)
- (300:66) 'siehe FAQ' => http://localhost:4000/de/wiki/FAQ#warum-sollte-ich-keine-drahtlosen-ger%C3%A4te-verwenden (HTTP 200 but missing anchor)
- (321:39) 'Die gold..' => http://localhost:4000/de/wiki/Client-Troubleshooting#der-sound-ist-gut-aber-es-ist-schwierig-im-takt-zu-bleiben (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Installation-for-Macintosh
- (251:0) 'Konfigur..' => http://localhost:4000/de/wiki/Software-Manual#sicherung-von-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Installation-for-Windows
- (251:0) 'Konfigur..' => http://localhost:4000/de/wiki/Software-Manual#sicherung-von-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/es/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://localhost:4000/es/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/fr/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://localhost:4000/fr/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Command-Line-Options
- (282:8) 'exécuter..' => http://localhost:4000/fr/wiki/Running-a-Server#server-mode-related-options (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Directories
- (244:5) 'Modes de..' => http://localhost:4000/fr/wiki/Running-a-Server#modes-de-serveur (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/FAQ
- (281:23) 'cet aper..' => http://localhost:4000/fr/wiki/Running-a-Server#modes-de-serveur (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Installation-for-Windows
- (303:66) 'connecté..' => http://localhost:4000/fr/wiki/Getting-Started#se-connecter-%C3%A0-un-serveur-et-tester-son-son (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Running-a-Server
- (357:138) 'la secti..' => http://localhost:4000/fr/wiki/Running-a-Server#modes-de-serveur (HTTP 200 but missing anchor)
- (387:19) 'options ..' => http://localhost:4000/fr/wiki/Running-a-Server#options-de-la-ligne-de-commande (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Server-Troubleshooting
- (275:12) 'redirige..' => http://localhost:4000/fr/wiki/Running-a-Server#redirection-de-port (HTTP 200 but missing anchor)

http://localhost:4000/it/wiki/Getting-Started
- (317:14) 'Golden R..' => http://localhost:4000/it/wiki/Client-Troubleshooting#you-all-sound-ok-but-its-hard-to-keep-together (HTTP 200 but missing anchor)

http://localhost:4000/it/wiki/Installation-for-Windows
- (287:61) 'connecte..' => http://localhost:4000/it/wiki/Getting-Started#connecting-to-a-server-and-testing-your-sound (HTTP 200 but missing anchor)

http://localhost:4000/ko_KR/wiki/Client-Troubleshooting
- (261:101) 'ASIO4ALL..' => http://localhost:4000/ko_KR/wiki/Installation-for-Windows#setting-up-asio4all (HTTP 200 but missing anchor)

http://localhost:4000/ko_KR/wiki/Installation-for-Android
- (235:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (243:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (278:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-Macintosh
- (235:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (243:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (267:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-Windows
- (235:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (243:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (351:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-iOS
- (235:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (243:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (298:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/nl/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://localhost:4000/nl/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/zh_CN/wiki/Getting-Started
- (235:40) 'FAQ' => http://localhost:4000/zh_CN/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E5%BA%94%E8%AF%A5%E4%BD%BF%E7%94%A8%E6%97%A0%E7%BA%BF%E8%AE%BE%E5%A4%87 (HTTP 200 but missing anchor)
- (236:38) 'FAQ' => http://localhost:4000/zh_CN/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E5%BA%94%E8%AF%A5%E4%BD%BF%E7%94%A8%E6%97%A0%E7%BA%BF%E8%AE%BE%E5%A4%87 (HTTP 200 but missing anchor)
- (285:20) '见FAQ' => http://localhost:4000/zh_CN/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E5%BA%94%E8%AF%A5%E5%90%AC%E8%87%AA%E5%B7%B1%E7%9A%84%E4%BF%A1%E5%8F%B7 (HTTP 200 but missing anchor)
- (299:122) '黄金法则' => http://localhost:4000/zh_CN/wiki/Client-Troubleshooting#%E4%BD%A0%E4%BB%AC%E5%90%AC%E8%B5%B7%E6%9D%A5%E9%83%BD%E4%B8%8D%E9%94%99%E4%BD%86%E5%BE%88%E9%9A%BE%E4%BF%9D%E6%8C%81%E5%9C%A8%E4%B8%80%E8%B5%B7 (HTTP 200 but missing anchor)

http://localhost:4000/zh_CN/wiki/Installation-for-Linux
- (249:30) '备份您的配置' => http://localhost:4000/zh_CN/wiki/Software-Manual#%E5%A4%87%E4%BB%BD-jamulus (HTTP 200 but missing anchor)
- (310:34) '故障排除页面' => http://localhost:4000/zh_CN/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4 (HTTP 404)

http://localhost:4000/zh_CN/wiki/Installation-for-Macintosh
- (249:13) '备份您的配置' => http://localhost:4000/zh_CN/wiki/Software-Manual#%E5%A4%87%E4%BB%BD-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/zh_CN/wiki/Installation-for-Windows
- (287:61) 'connecte..' => http://localhost:4000/zh_CN/wiki/Getting-Started#connecting-to-a-server-and-testing-your-sound (HTTP 200 but missing anchor)


Summary of most serious issues:

http://localhost:4000/ko_KR/wiki/Installation-for-Android
- (235:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (243:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (278:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-Macintosh
- (235:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (243:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (267:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-Windows
- (235:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (243:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (351:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-iOS
- (235:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (243:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (298:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/zh_CN/wiki/Installation-for-Linux
- (310:34) '故障排除页面' => http://localhost:4000/zh_CN/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4 (HTTP 404)

Errors. Checked 37277 links, 633 destination URLs (732 ignored), 2 have errors, 27 have warnings.
```

**Comment by pljones** [comment]
> Linkcheck errors:
> 
> ```
> ...
> Errors. Checked 37277 links, 633 destination URLs (732 ignored), 2 have errors, 27 have warnings.
> ```

It would be good if it _totally ignored_ "localhost" links...

**Comment by ann0see** [comment]
I ran this locally so localhost is present everywhere.

**Comment by pljones** [comment]
> I ran this locally so localhost is present everywhere.

If they're relative links or even rooted links, the hostname shouldn't be present...  The link checker should then be able to tell whether it's meant to look within the built output for the target or on the wider Web.

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
I will declare a website freeze NOW

**Comment by henkdegroot** [comment]
@ann0see, is it a manual process to get the weblate PR generated for the website or has that been "paused"? Waiting for the weblate PR to appear so I can test.

**Comment by ignotus666** [comment]
@henkdegroot I just did it - there should be a PR now.

**Comment by ann0see** [comment]
I have also noticed that. Probably something needs to be configured on Weblate. 
I think initially we configured putting one day into one commit.

**Comment by pljones** [comment]
As per app translations - is anything on-going on Weblate for the website and, if not, are we ready to finalise the release?

**Comment by trebmuh** [comment]
For the French translations (website and app), I've finished to review the French translation for the website pages, so it's all good on this edge. For the app, I'm on the way to finished to review the French translations. Should be done in a few days if everything is going well.

**Comment by henkdegroot** [comment]
I have noticed to broken links in the Running a Server webpage. Should I create an issue for this or will that be taken care of when the links are checked?

**Comment by ann0see** [comment]
Once the Weblate PR is merged, we'd fix the links. But feel free to already fix some in a separate PR

**Comment by henkdegroot** [comment]
PR #960 created to fix two broken links in the English Running a Server page.

**Comment by trebmuh** [comment]
> For the French translations (website and app), I've finished to review the French translation for the website pages, so it's all good on this edge. For the app, I'm on the way to finished to review the French translations. Should be done in a few days if everything is going well.

Everything's done now.

**Comment by jujudusud** [comment]
After #960 was merged, I updated the links for french website too.

**Comment by henkdegroot** [comment]
> I updated the links for french website too.

@jujudusud  I noticed 1 link is not correct, In the Running a Server page, the link point to Running-a-Server#modes-du-serveur while it should be Running-a-Server#modes-de-serveur. I don't know how to best identify the line this is in, thinking you can find it using the search option.

**Comment by jujudusud** [comment]
> I noticed 1 link is not correct, In the Running a Server page, the link point to Running-a-Server#modes-du-serveur while it should be Running-a-Server#modes-de-serveur. I don't know how to best identify the line this is in, thinking you can find it using the search option.

@henkdegroot : Is there anything else than what's in this commit: https://github.com/jamulussoftware/jamuluswebsite/pull/961/commits/f9c91f078d8c77a98e846dea6eb8b4702edfaa0e ?

**Comment by pljones** [comment]
Should the `id="<id string>"` values be translatable?  If they weren't, there'd be less likelihood of link breakage (i.e. just the English).  The link text (i.e. `<link text>` in `<a href="<someUrl>#<id string>"><link text></a>`) would still need translating, of course.

**Comment by ann0see** [comment]
I think jekyll automatically sets them - especially for headlines. We could probably set it like classes, but that would still show up in the translation.

**Comment by henkdegroot** [comment]
> Is there anything else than what's in this commit: [f9c91f0](https://github.com/jamulussoftware/jamuluswebsite/commit/f9c91f078d8c77a98e846dea6eb8b4702edfaa0e) ?

@jujudusud this change has broken the links in the Directories and FAQ page. Here is the linkcheck output for fr (first broken link exists in all languages, so that can be ignored):

http://127.0.0.1:4000/fr/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://127.0.0.1:4000/fr/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://127.0.0.1:4000/fr/wiki/Command-Line-Options
- (289:8) 'exécuter..' => http://127.0.0.1:4000/fr/wiki/Running-a-Server#server-mode-related-options (HTTP 200 but missing anchor)

http://127.0.0.1:4000/fr/wiki/Directories
- (244:5) 'Modes de..' => http://127.0.0.1:4000/fr/wiki/Running-a-Server#modes-de-serveur (HTTP 200 but missing anchor)

http://127.0.0.1:4000/fr/wiki/FAQ
- (281:23) 'cet aper..' => http://127.0.0.1:4000/fr/wiki/Running-a-Server#modes-de-serveur (HTTP 200 but missing anchor)

http://127.0.0.1:4000/fr/wiki/Installation-for-Windows
- (299:78) 'connecté..' => http://127.0.0.1:4000/fr/wiki/Getting-Started#se-connecter-%C3%A0-un-serveur-et-tester-son-son (HTTP 200 but missing anchor)

http://127.0.0.1:4000/fr/wiki/Running-a-Server
- (359:138) 'la secti..' => http://127.0.0.1:4000/fr/wiki/Running-a-Server#modes-de-serveur (HTTP 200 but missing anchor)
- (383:19) 'options ..' => http://127.0.0.1:4000/fr/wiki/Running-a-Server#options-de-la-ligne-de-commande (HTTP 200 but missing anchor)
- (492:344) 'options ..' => http://127.0.0.1:4000/fr/wiki/Running-a-Server#options-liees-au-mode-serveur (HTTP 200 but missing anchor)

http://127.0.0.1:4000/fr/wiki/Server-Troubleshooting
- (275:12) 'redirige..' => http://127.0.0.1:4000/fr/wiki/Running-a-Server#redirection-de-port (HTTP 200 but missing anchor)

In case it helps, here is the full linkcheck output in a text file:
[linkckeck-output.txt](https://github.com/jamulussoftware/jamuluswebsite/files/12385252/linkckeck-output.txt)

**Comment by ann0see** [comment]
Updated linkcheck output:
```

http://localhost:4000/de/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://localhost:4000/de/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Client-Troubleshooting
- (261:101) 'ASIO4ALL..' => http://localhost:4000/de/wiki/Installation-for-Windows#setting-up-asio4all (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Command-Line-Options
- (278:113) 'Tipps & ..' => http://localhost:4000/de/wiki/Tips-Tricks-More#verwendung-von-ctrlmidich-f%C3%BCr-midi-controller (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/FAQ
- (263:44) 'Goldene ..' => http://localhost:4000/de/wiki/Client-Troubleshooting#der-sound-ist-gut-aber-es-ist-schwierig-im-takt-zu-bleiben (HTTP 200 but missing anchor)
- (281:34) 'diese Üb..' => http://localhost:4000/de/wiki/Running-a-Server#server-typen (HTTP 200 but missing anchor)
- (288:4) 'Goldene ..' => http://localhost:4000/de/wiki/Client-Troubleshooting#der-sound-ist-gut-aber-es-ist-schwierig-im-takt-zu-bleiben (HTTP 200 but missing anchor)
- (309:0) 'Goldene ..' => http://localhost:4000/de/wiki/Client-Troubleshooting#der-sound-ist-gut-aber-es-ist-schwierig-im-takt-zu-bleiben (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Getting-Started
- (320:35) 'die gold..' => http://localhost:4000/de/wiki/Client-Troubleshooting#der-sound-ist-gut-aber-es-ist-schwierig-im-takt-zu-bleiben (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Installation-for-Linux
- (246:51) 'Konfigur..' => http://localhost:4000/de/wiki/Software-Manual#sicherung-von-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Installation-for-Macintosh
- (247:0) 'Konfigur..' => http://localhost:4000/de/wiki/Software-Manual#sicherung-von-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Installation-for-Windows
- (247:0) 'Konfigur..' => http://localhost:4000/de/wiki/Software-Manual#sicherung-von-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Running-a-Server
- (300:146) 'Tips and..' => http://localhost:4000/de/wiki/Tips-Tricks-More#have-an-undisturbed-session-on-any-server (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Server-Troubleshooting
- (267:511) 'forward ..' => http://localhost:4000/de/wiki/Unregistered-Servers#port-forwarding (HTTP 200 but missing anchor)
- (281:508) 'this guide' => http://localhost:4000/de/wiki/Unregistered-Servers#dynamic-dns-and-why-you-will-probably-need-it (HTTP 200 but missing anchor)
- (289:42) 'port for..' => http://localhost:4000/de/wiki/Unregistered-Servers#port-forwarding (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Software-Manual
- (610:305) 'Tips & T..' => http://localhost:4000/de/wiki/Tips-Tricks-More#using-ctrlmidich-for-midi-controllers (HTTP 200 but missing anchor)

http://localhost:4000/es/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://localhost:4000/es/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/fr/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://localhost:4000/fr/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Command-Line-Options
- (289:8) 'exécuter..' => http://localhost:4000/fr/wiki/Running-a-Server#options-liees-au-mode-serveur (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Installation-for-Windows
- (299:78) 'connecté..' => http://localhost:4000/fr/wiki/Getting-Started#se-connecter-%C3%A0-un-serveur-et-tester-son-son (HTTP 200 but missing anchor)

http://localhost:4000/it/wiki/Getting-Started
- (317:14) 'Golden R..' => http://localhost:4000/it/wiki/Client-Troubleshooting#you-all-sound-ok-but-its-hard-to-keep-together (HTTP 200 but missing anchor)

http://localhost:4000/it/wiki/Installation-for-Windows
- (283:61) 'connecte..' => http://localhost:4000/it/wiki/Getting-Started#connecting-to-a-server-and-testing-your-sound (HTTP 200 but missing anchor)

http://localhost:4000/ko_KR/wiki/Client-Troubleshooting
- (261:101) 'ASIO4ALL..' => http://localhost:4000/ko_KR/wiki/Installation-for-Windows#setting-up-asio4all (HTTP 200 but missing anchor)

http://localhost:4000/nl/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://localhost:4000/nl/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/zh_CN/wiki/Getting-Started
- (235:40) 'FAQ' => http://localhost:4000/zh_CN/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E5%BA%94%E8%AF%A5%E4%BD%BF%E7%94%A8%E6%97%A0%E7%BA%BF%E8%AE%BE%E5%A4%87 (HTTP 200 but missing anchor)
- (236:38) 'FAQ' => http://localhost:4000/zh_CN/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E5%BA%94%E8%AF%A5%E4%BD%BF%E7%94%A8%E6%97%A0%E7%BA%BF%E8%AE%BE%E5%A4%87 (HTTP 200 but missing anchor)
- (285:20) '见FAQ' => http://localhost:4000/zh_CN/wiki/FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E5%BA%94%E8%AF%A5%E5%90%AC%E8%87%AA%E5%B7%B1%E7%9A%84%E4%BF%A1%E5%8F%B7 (HTTP 200 but missing anchor)
- (299:122) '黄金法则' => http://localhost:4000/zh_CN/wiki/Client-Troubleshooting#%E4%BD%A0%E4%BB%AC%E5%90%AC%E8%B5%B7%E6%9D%A5%E9%83%BD%E4%B8%8D%E9%94%99%E4%BD%86%E5%BE%88%E9%9A%BE%E4%BF%9D%E6%8C%81%E5%9C%A8%E4%B8%80%E8%B5%B7 (HTTP 200 but missing anchor)

http://localhost:4000/zh_CN/wiki/Installation-for-Macintosh
- (245:13) '备份您的配置' => http://localhost:4000/zh_CN/wiki/Software-Manual#%E5%A4%87%E4%BB%BD-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/zh_CN/wiki/Installation-for-Windows
- (283:61) 'connecte..' => http://localhost:4000/zh_CN/wiki/Getting-Started#connecting-to-a-server-and-testing-your-sound (HTTP 200 but missing anchor)

Warnings. Checked 38072 links, 642 destination URLs (748 ignored), 30 have warnings.
```

**Comment by ann0see** [comment]
The ko_KR ones have been fixed. The other ones are cosmetical

**Comment by jujudusud** [comment]
I don't know how to fix this one:
`http://localhost:4000/fr/kb/2021/04/18/Jamulus-Video.html
- (345:7) 'Tips and..' => http://localhost:4000/fr/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)`

As this is not a translated file.

The other are ok in 098cc5c and 4c22448

**Comment by henkdegroot** [comment]
> I don't know how to fix this one:
> `http://localhost:4000/fr/kb/2021/04/18/Jamulus-Video.html

I believe these cannot be fixed

**Comment by ann0see** [comment]
Un-Drafted. As soon as we build the release, the release links must be updated and this PR squash merged.
Then the state of the release branch FORCE PUSHED to next-release
Then weblate for the website RESET and rebased on the new state of next-release.

**Pull request merged**
