### PR TITLE
[Translate FR] add translated fr-Command-Line-Options.md

### PR DESCRIPTION
**Pull request by jujudusud**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

Adding translation in FR for command line options file.

### CODE REVIEW

**Comment by trebmuh** [comment]
@ann0see why does the wiki/fr/fr-Command-Line-Options.md needs to be completely retranslated? I've already translated it in January here: https://github.com/jamulussoftware/jamuluswebsite/pull/240

Note : I didn't look precisely at the rest. I'm moving from a place to another and I'm starting a new job soon, so I've got close to no time now.

**Comment by ann0see** [comment]
@trebmuh Currently I'm not the right person to comment on this. I think this is somehow related to a restructuring of the wiki. Tagging @gilgongo here.

**Comment by gilgongo** [comment]
There were some options missing, and grouping them all in the same way as -h (so you can easily see which are related to client, server or both) is a prelude to putting the contents into the relevant client and (forthcoming) server manuals at some point.

**Comment by trebmuh** [comment]
@ann0see ok, thank you

@gilgongo I'm not talking about the fact that some changes have been made into the English version of the page. This is normal. I'm talking about the fact that I've already translated the whole page [3 months ago](https://github.com/jamulussoftware/jamuluswebsite/pull/240) and now, it's like that everything needs to be done again rather than modifying a few lines. Why that? I'd expect the English page to be modified where needed, and then the French translation (and other translations) to follow, not the whole thing to be deleted and then, all the work need to be done again and again. Please, explain.

**Comment by gilgongo** [comment]
@trebmuh I think you may be referring to [this discussion](https://github.com/jamulussoftware/jamulus/discussions/1302#discussioncomment-512715), which resulted in [this PR](https://github.com/jamulussoftware/jamuluswebsite/pull/400) which removed a number of out of date translations.

**Pull request closed without merging**
