### PR TITLE
919 Update "--directoryserver" to "--directoryaddress"

### LINKED ISSUE #919: --directoryaddress replaces the --directoryserver command line option
`--directoryaddress` replaces the `--directoryserver` command line option, so the documentation where this is mentioned needs updating.

(See https://github.com/jamulussoftware/jamulus/pull/3017)

### PR DESCRIPTION
**Pull request by pljones**
**Short description of changes**

Bring documentation inline with latest code.

**Context: Fixes an issue? Related issues**

https://github.com/jamulussoftware/jamulus/pull/3017 updated Jamulus to use `--directoryaddress` for the Directory address command line argument.

**Status of this Pull Request**

Text files updated.

**What is missing until this pull request can be merged?**

Reviews.

**Does this need translation?**

Probably not - this is an untranslatable string.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Review by ann0see — COMMENTED** [review]
Did you check that there isn't any other location? I quickly checked if there is a Include-Server-Commands file or similar, but there isn't.

(I might run the grep later on)

**Comment by pljones** [comment]
> Did you check that there isn't any other location? I quickly checked if there is a Include-Server-Commands file or similar, but there isn't.
> 
> (I might run the grep later on)

In `jamulussoftware/jamuluswebsite` it should all be covered.  My original grep / sed had not limited to `src` - I'd also included the `po` files:
```sh
 sed -i -e 's/--directoryserver/--directoryaddress/g' $(grep -lr -- --directoryserver)
```
The `grep` should have been `grep -lr -- --directoryserver | grep -v '/po/\|^\.git'`.

**Comment by ignotus666** [comment]
> I quickly checked if there is a Include-Server-Commands file or similar, but there isn't.

It should be removed from the po file directories - I wasn't aware that this file didn't exist in `wiki/en` any more. It's not on Weblate so no harm done.

**Review by ann0see — APPROVED** [review]
Ok. Seems good then

**Pull request merged**
