### PR TITLE
Update it-Getting-Started.md

### PR DESCRIPTION
**Pull request by vdellamea**
Some small correction plus the main one: the meaning of footnote 1 was reversed in Italian.

### CODE REVIEW

**Comment by ann0see** [comment]
Thanks for your changes! I assume it's a problem with the page which is live on jamulus.io?

**Comment by vdellamea** [comment]
Hi,
Yes, I suppose this is the way to contribute to translations;
Vincenzo 

Inviato da iPhone

**Comment by ann0see** [comment]
Because of translations, our process is a bit complicated ;-). If the change you made doesn’t affect other languages, you should open the PR to the release branch (I know it’s far from obvious). 

https://github.com/jamulussoftware/jamuluswebsite/blob/changes/CONTRIBUTING.md#branches-translation-and-development-process

**Comment by ann0see** [comment]
Concerning the content:

I‘ve now assigned the initial Italian translator to this issue, but I‘m quite sure that we can add your changes to the site which is live currently. 

If you want, I can also take care of it and upload your changes?

**Comment by vdellamea** [comment]
yes thanks - for the next contributions, I will try to follow the right path;
thanks
Vincenzo

**Comment by ann0see** [comment]
> yes thanks - for the next contributions, I will try to follow the right path;

No problem ;-). I will merge this to changes and cherry-pick it to release.


If @dzpex has any proposed changes to this, please comment here.

**Pull request merged**
