### PR TITLE
[fr] UPDATE index (closed and reopened with clean branch)

### PR DESCRIPTION
**Pull request by gegeweb**
* GNU/Linux -> Linux as in EN and other languages
* Add no breaking space (`&nbsp`) to follow the French typographical rules and avoid line break before punctuation.

/ping @trebmuh

### CODE REVIEW

**Review by trebmuh — APPROVED** [review]
All good for me :+1:

**Comment by trebmuh** [comment]
@ann0see (double-checking) is that normal that this PR now add the fr-Privacy-Statement.md file while it has already been merged in #123 ?

**Comment by ann0see** [comment]
> is that normal that this PR now add the fr-Privacy-Statement.md file while it has already been merged in #123 ?

no. That's not normal. I will look what's wrong (I changed the branch of this pr. Maybe release is not up to date)

**Review by ann0see — CHANGES_REQUESTED** [review]
@gegeweb 

Do you know why fr-Privacy-Statement.md is here too?

@trebmuh I can see this file on the release branch. So I don't know what the issue is.

**Comment by trebmuh** [comment]
OK

**Comment by gegeweb** [comment]
> @gegeweb
> 
> Do you know why fr-Privacy-Statement.md is here too?

No. Was not here.
Perhaps a pull (merge) with the release branch will solve this.
I'll try.

> 
> @trebmuh I can see this file on the release branch. So I don't know what the issue is.

**Comment by gegeweb** [comment]
The best is probably to close this PR, and recreate a clean one from the release up to date branch.

**Comment by ann0see** [comment]
> The best is probably to close this PR, and recreate a clean one from the release up to date branch.

Yes or something like a fit rebase (not sure if that's the right way to do it).

**Comment by gegeweb** [comment]
Closed this and created a new one. More fast than « _jouer les apprentis sorciers_ » with git. ;)

**Pull request closed without merging**
