### PR TITLE
RELEASE: Update website for r3.9.1 SQUASH MERGE ONLY

### PR DESCRIPTION
**Pull request by ann0see**
We are pleased to announce the start of the translation phase of r3.9.1. Please verify that this Pull Request contains all the relevant changes for r3.9.1. 

**Short description of changes**
This contains the 3.9.1 release content. Please only SQUASH MERGE this PR as it contains sensitive E-Mail content!!!

**Context: Fixes an issue? Related issues**
Release issue: https://github.com/jamulussoftware/jamulus/issues/2813

**Status of this Pull Request**
See: https://github.com/jamulussoftware/jamulus/issues/2813

**What is missing until this pull request can be merged?**
Testing. This PR MUST be squash merged as it contains sensitive E-Mails

**Does this need translation?**

Invalid

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Comment by ann0see** [comment]
Output of linkchecker:

Crawling...

http://localhost:4000/de/kb/2021/04/18/Jamulus-Video.html
- (328:7) 'Tips and..' => http://localhost:4000/de/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Command-Line-Options
- (254:282) 'Server T..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (262:176) 'notes' => http://localhost:4000/de/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (263:232) 'Options' => http://localhost:4000/de/wiki/Running-a-Server#options (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Directories
- (227:71) 'Server T..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/FAQ
- (249:267) 'this ove..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Installation-for-Linux
- (233:30) 'back up ..' => http://localhost:4000/de/wiki/Software-Manual#backing-up-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Running-a-Server
- (283:270) 'SOLO Tec..' => http://localhost:4000/de/wiki/Tips-Tricks-More#eine-ungest%C3%B6rte-sitzung-auf-einem-beliebigen-server-einrichten (HTTP 200 but missing anchor)
- (422:24) 'Directory' => http://localhost:4000/de/wiki/Running-a-Server#3-directory (HTTP 200 but missing anchor)
- (564:282) 'Server T..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (572:176) 'notes' => http://localhost:4000/de/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (573:232) 'Options' => http://localhost:4000/de/wiki/Running-a-Server#options (HTTP 200 but missing anchor)

http://localhost:4000/es/kb/2021/04/18/Jamulus-Video.html
- (328:7) 'Tips and..' => http://localhost:4000/es/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/es/wiki/Command-Line-Options
- (246:282) 'Server T..' => http://localhost:4000/es/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (254:176) 'notes' => http://localhost:4000/es/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (255:232) 'Options' => http://localhost:4000/es/wiki/Running-a-Server#options (HTTP 200 but missing anchor)
- (263:167) 'Notas so..' => http://localhost:4000/es/wiki/Custom-Directories#notas-sobre-directorios (HTTP 404)

http://localhost:4000/es/wiki/Running-a-Server
- (562:282) 'Server T..' => http://localhost:4000/es/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (570:176) 'notes' => http://localhost:4000/es/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (571:232) 'Options' => http://localhost:4000/es/wiki/Running-a-Server#options (HTTP 200 but missing anchor)
- (579:167) 'Notas so..' => http://localhost:4000/es/wiki/Custom-Directories#notas-sobre-directorios (HTTP 404)

http://localhost:4000/fr/kb/2021/04/18/Jamulus-Video.html
- (328:7) 'Tips and..' => http://localhost:4000/fr/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Command-Line-Options
- (246:282) 'Server T..' => http://localhost:4000/fr/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (254:176) 'notes' => http://localhost:4000/fr/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (263:171) 'Notes on..' => http://localhost:4000/fr/wiki/Directories#points-to-note-about-directories (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Directories
- (227:83) 'Types de..' => http://localhost:4000/fr/wiki/Running-a-Server#types-de-serveurs (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Running-a-Server
- (561:282) 'Server T..' => http://localhost:4000/fr/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (569:176) 'notes' => http://localhost:4000/fr/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (578:171) 'Notes on..' => http://localhost:4000/fr/wiki/Directories#points-to-note-about-directories (HTTP 200 but missing anchor)

http://localhost:4000/nl/kb/2021/04/18/Jamulus-Video.html
- (328:7) 'Tips and..' => http://localhost:4000/nl/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/nl/wiki/Command-Line-Options
- (246:282) 'Server T..' => http://localhost:4000/nl/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (254:176) 'notes' => http://localhost:4000/nl/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (255:232) 'Options' => http://localhost:4000/nl/wiki/Running-a-Server#options (HTTP 200 but missing anchor)

http://localhost:4000/nl/wiki/Directories
- (227:71) 'Server T..' => http://localhost:4000/nl/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)

http://localhost:4000/nl/wiki/FAQ
- (249:267) 'this ove..' => http://localhost:4000/nl/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)

http://localhost:4000/nl/wiki/Running-a-Server
- (281:258) 'solotech..' => http://localhost:4000/nl/wiki/Tips-Tricks-More#zorg-voor-een-ongestoorde-sessie-op-elke-server (HTTP 200 but missing anchor)
- (420:24) 'Directory' => http://localhost:4000/nl/wiki/Running-a-Server#3-directory (HTTP 200 but missing anchor)
- (562:282) 'Server T..' => http://localhost:4000/nl/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (570:176) 'notes' => http://localhost:4000/nl/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (571:232) 'Options' => http://localhost:4000/nl/wiki/Running-a-Server#options (HTTP 200 but missing anchor)

http://localhost:4000/nl/wiki/Software-Manual
- (366:236) 'Mute Mys..' => http://localhost:4000/nl/wiki/Software-Manual#mute-myself-button (HTTP 200 but missing anchor)


Summary of most serious issues:

http://localhost:4000/es/wiki/Command-Line-Options
- (263:167) 'Notas so..' => http://localhost:4000/es/wiki/Custom-Directories#notas-sobre-directorios (HTTP 404)

http://localhost:4000/es/wiki/Running-a-Server
- (579:167) 'Notas so..' => http://localhost:4000/es/wiki/Custom-Directories#notas-sobre-directorios (HTTP 404)


Stats:
   28427 links
     511 destination URLs
     646 URLs ignored
      39 warnings
       1 errors

**Review by pljones — DISMISSED** [review]

**Comment by ann0see** [comment]
@ignotus666 there are broken links in the es version of the site leading to 404's. Please have a look at them:

Done crawling.                   

http://localhost:4000/de/kb/2021/04/18/Jamulus-Video.html
- (328:7) 'Tips and..' => http://localhost:4000/de/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Client-Troubleshooting
- (242:101) 'ASIO4ALL..' => http://localhost:4000/de/wiki/Installation-for-Windows#setting-up-asio4all (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Command-Line-Options
- (254:282) 'Server T..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (262:176) 'notes' => http://localhost:4000/de/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (263:232) 'Options' => http://localhost:4000/de/wiki/Running-a-Server#options (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Directories
- (227:71) 'Server T..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/FAQ
- (249:267) 'this ove..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Installation-for-Linux
- (233:30) 'back up ..' => http://localhost:4000/de/wiki/Software-Manual#backing-up-jamulus (HTTP 200 but missing anchor)

http://localhost:4000/de/wiki/Running-a-Server
- (283:524) 'Server T..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (422:24) 'Directory' => http://localhost:4000/de/wiki/Running-a-Server#3-directory (HTTP 200 but missing anchor)
- (564:282) 'Server T..' => http://localhost:4000/de/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (572:176) 'notes' => http://localhost:4000/de/wiki/Running-a-Server#delay-panning (HTTP 200 but missing anchor)
- (573:232) 'Options' => http://localhost:4000/de/wiki/Running-a-Server#options (HTTP 200 but missing anchor)

http://localhost:4000/es/kb/2021/04/18/Jamulus-Video.html
- (328:7) 'Tips and..' => http://localhost:4000/es/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/es/wiki/Command-Line-Options
- (263:167) 'Notas so..' => http://localhost:4000/es/wiki/Custom-Directories#notas-sobre-directorios (HTTP 404)

http://localhost:4000/es/wiki/Running-a-Server
- (579:167) 'Notas so..' => http://localhost:4000/es/wiki/Custom-Directories#notas-sobre-directorios (HTTP 404)

http://localhost:4000/fr/kb/2021/04/18/Jamulus-Video.html
- (328:7) 'Tips and..' => http://localhost:4000/fr/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Command-Line-Options
- (263:173) 'Notes su..' => http://localhost:4000/fr/wiki/Directories#points-a-noter-concernant-des-annuaires (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Directories
- (227:83) 'Types de..' => http://localhost:4000/fr/wiki/Running-a-Server#types-de-serveurs (HTTP 200 but missing anchor)

http://localhost:4000/fr/wiki/Running-a-Server
- (578:173) 'Notes su..' => http://localhost:4000/fr/wiki/Directories#points-a-noter-concernant-des-annuaires (HTTP 200 but missing anchor)

http://localhost:4000/ko_KR/wiki/Command-Line-Options
- (238:236) '팁 & 트릭' => http://localhost:4000/ko_KR/wiki/Tips-Tricks-More#using-ctrlmidich-for-midi-%20%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC (HTTP 200 but missing anchor)
- (247:133) '이 가이드' => http://localhost:4000/ko_KR/wiki/%EB%94%94%EB%A0%89%ED%84%B0%EB%A6%AC (HTTP 404)
- (255:189) '옵션' => http://localhost:4000/ko_KR/wiki/%EC%84%9C%EB%B2%84%20#%EC%98%B5%EC%85%98%20%EC%8B%A4%ED%96%89 (HTTP 404)
- (263:126) '디렉터리에 대한..' => http://localhost:4000/ko_KR/wiki/Directories#points-to-note-about-directories (HTTP 200 but missing anchor)

http://localhost:4000/ko_KR/wiki/Directories
- (219:3) '서버 관리' => http://localhost:4000/ko_KR/wiki/%EC%84%9C%EB%B2%84%20%EC%8B%A4%ED%96%89 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Getting-Started
- (239:56) 'iOS' => http://localhost:4000/ko_KR/wiki/iOS%EC%9A%A9%20%EC%84%A4%EC%B9%98 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-Linux
- (219:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (227:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (288:160) '문제 해결 페이지' => http://localhost:4000/ko_KR/wiki/%ED%81%B4%EB%9D%BC%EC%9D%B4%EC%96%B8%ED%8A%B8%20%EB%AC%B8%EC%A0%9C%20%ED%95%B4%EA%B2%B0 (HTTP 404)
- (294:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-Windows
- (271:61) 'connecte..' => http://localhost:4000/ko_KR/wiki/Getting-Started#connecting-to-a-server-and-testing-your-sound (HTTP 200 but missing anchor)

http://localhost:4000/ko_KR/wiki/Running-a-Server
- (579:171) 'Notes on..' => http://localhost:4000/ko_KR/wiki/Directories#points-to-note-about-directories (HTTP 200 but missing anchor)

http://localhost:4000/ko_KR/wiki/Server-Bandwidth
- (219:3) '서버 관리' => http://localhost:4000/ko_KR/wiki/%EC%84%9C%EB%B2%84%20%EC%8B%A4%ED%96%89 (HTTP 404)

http://localhost:4000/nl/kb/2021/04/18/Jamulus-Video.html
- (328:7) 'Tips and..' => http://localhost:4000/nl/wiki/Tips-Tricks-More#using-jamulus-audio-in-zoom-or-other-meeting-apps (HTTP 200 but missing anchor)

http://localhost:4000/nl/wiki/Command-Line-Options
- (246:282) 'Server T..' => http://localhost:4000/nl/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (255:232) 'Options' => http://localhost:4000/nl/wiki/Running-a-Server#options (HTTP 200 but missing anchor)

http://localhost:4000/nl/wiki/Running-a-Server
- (562:282) 'Server T..' => http://localhost:4000/nl/wiki/Running-a-Server#server-types (HTTP 200 but missing anchor)
- (571:232) 'Options' => http://localhost:4000/nl/wiki/Running-a-Server#options (HTTP 200 but missing anchor)


Summary of most serious issues:

http://localhost:4000/es/wiki/Command-Line-Options
- (263:167) 'Notas so..' => http://localhost:4000/es/wiki/Custom-Directories#notas-sobre-directorios (HTTP 404)

http://localhost:4000/es/wiki/Running-a-Server
- (579:167) 'Notas so..' => http://localhost:4000/es/wiki/Custom-Directories#notas-sobre-directorios (HTTP 404)

http://localhost:4000/ko_KR/wiki/Command-Line-Options
- (247:133) '이 가이드' => http://localhost:4000/ko_KR/wiki/%EB%94%94%EB%A0%89%ED%84%B0%EB%A6%AC (HTTP 404)
- (255:189) '옵션' => http://localhost:4000/ko_KR/wiki/%EC%84%9C%EB%B2%84%20#%EC%98%B5%EC%85%98%20%EC%8B%A4%ED%96%89 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Directories
- (219:3) '서버 관리' => http://localhost:4000/ko_KR/wiki/%EC%84%9C%EB%B2%84%20%EC%8B%A4%ED%96%89 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Getting-Started
- (239:56) 'iOS' => http://localhost:4000/ko_KR/wiki/iOS%EC%9A%A9%20%EC%84%A4%EC%B9%98 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Installation-for-Linux
- (219:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (227:3) '시작하기' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)
- (288:160) '문제 해결 페이지' => http://localhost:4000/ko_KR/wiki/%ED%81%B4%EB%9D%BC%EC%9D%B4%EC%96%B8%ED%8A%B8%20%EB%AC%B8%EC%A0%9C%20%ED%95%B4%EA%B2%B0 (HTTP 404)
- (294:3) '시작하기 페이지' => http://localhost:4000/ko_KR/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0 (HTTP 404)

http://localhost:4000/ko_KR/wiki/Server-Bandwidth
- (219:3) '서버 관리' => http://localhost:4000/ko_KR/wiki/%EC%84%9C%EB%B2%84%20%EC%8B%A4%ED%96%89 (HTTP 404)

Errors. Checked 28429 links, 517 destination URLs (649 ignored), 7 have errors, 27 have warnings.

**Comment by ann0see** [comment]
The site doesn't seem right locally. Please do not merge yet.

**Comment by ann0see** [comment]
There are still some minor broken link issues (and major ones in the ko_KR translation). However, they can be fixed post release.

**Pull request merged**
