### PR TITLE
Update PR template to include note about Weblate

### PR DESCRIPTION
**Pull request by ignotus666**
**Short description of changes**
Update this PR message template to include warning about merging Weblate PRs first if the change affects translations.

**Context: Fixes an issue? Related issues**
Should help prevent conflicts caused by skipping this step.

**Status of this Pull Request**

**What is missing until this pull request can be merged?**

**Does this need translation?**

NO

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Comment by ignotus666** [comment]
Maybe we could create a label too, something like "Merge weblate translations first" or something like that? It could probably be automated - if the workflow detects changes to translatable docs (it already does that), add the label too.

**Review by ann0see — COMMENTED** [review]
Not a big fan of that although it’s an easy start. I think a label + failed check would be better as it disables the merge button. Or something like this:

if(weblate has open PR and this PR changes English documentation) {
fail check "Weblate merge"
}

Mark the "Weblate merge" check as compulsory on GitHub.

**Comment by ignotus666** [comment]
> if(weblate has open PR and this PR changes English documentation) {
> fail check "Weblate merge"
> }
> 
> Mark the "Weblate merge" check as compulsory on GitHub.

If I understand that right, wouldn't it require re-running the workflow after the hypothetical Weblate PR has been merged?

**Comment by ann0see** [comment]
Probably yes. Although there might be ways around that (Weblate PR merge check triggers other check)

**Pull request closed without merging**
