### PR TITLE
Update en-Installation-for-Linux.md

### PR DESCRIPTION
**Pull request by yapsr**
I ran into an error message compiling on Debian Buster: "Project ERROR: jack development package not found" and want to add my solution to this problem.

### CODE REVIEW

**Comment by ann0see** [comment]
Thanks for raising this issue. At least for me, I didn't have to do that on Debian 10. Are you sure that it's a general issue others might also face?

**Comment by ann0see** [comment]
@gilgongo Merge?

**Comment by gilgongo** [comment]
This is the first time I've see this issue raised. Debian Buster isn't exactly an obscure distro (I didn't even know the PKG_CONFIG_PATH envvar was a thing). Are you *sure* this isn't some local issue on the machine? I wouldn't want to clutter up the docs with stuff like this if we can help it. If installation issues arise in some cases, they can be handled on the forums, no?

**Comment by yapsr** [comment]
@gilgongo Maybe you're right. I did not experience this issue on a different Debian 10 distro.

**Comment by ann0see** [comment]
@yaspr I assume it's not a general problem then?

**Comment by trebmuh** [comment]
My 2 cents: on the jamulus package I'm maintaining for LibraZiK-3 which is based on Debian Buster, I'm not using any magics around pkg-config. It then looks to me that this is a locale issue more than a general one.

**Comment by ann0see** [comment]
@yapsr would you be ok if we close this PR (if it's not a general issue?)

**Comment by yapsr** [comment]
Yes, you can close it.

**Comment by ann0see** [comment]
Ok. It's closed now. But nevertheless: thank you!

**Pull request closed without merging**
