### PR TITLE
[en] Update en-Software-Manual.md

### PR DESCRIPTION
**Pull request by trebmuh**
* one typo (maxmium)
* one little improvement (shift-right-click)
* one consistancy across the doc (JACK/Jack)

I've made the speed test link to go to https://librespeed.org/ rather than http://speedtest.net since it(s free software, and the "free as a free beer" speed test websites are often IP tracker, bitcoin mining,... stuff.

### CODE REVIEW

**Comment by ann0see** [comment]
No problem for me. But I think this is for @gilgongo

**Comment by ann0see** [comment]
Could you please rename it so that it starts with [en]?

**Comment by ignotus666** [comment]
Bar the typo, shouldn't this be going into 'changes'?

**Comment by trebmuh** [comment]
@ann0see @gilgongo let me know if the target branch need to be changed

**Comment by ann0see** [comment]
>  shouldn't this be going into 'changes'?

Yes. Since the speedtest url was changed.

**Comment by trebmuh** [comment]
closing here, see #148 for a PR against "changes"

**Pull request closed without merging**
