### PR TITLE
Better local monitoring test

### PR DESCRIPTION
**Pull request by gilgongo**
From [Chris Rimple](https://sourceforge.net/p/llcon/discussion/software/thread/166288d63e/#e047)

### CODE REVIEW

**Review by ann0see — APPROVED** [review]
Yes. This sounds logical. There's another todo: the recording feature might need to be updated (siguser2 command on a headless server etc. It's not well documented at the moment)

**Comment by gilgongo** [comment]
[There's this](https://jamulus.io/wiki/Server-Linux#controlling-recordings) (also linked to from the Windows/Mac server page) - seems OK to me. Is there something missing?

**Comment by ann0see** [comment]
Argh. Missed that. I thought it was on the tips page. Probably we need to re-think the structure of the Wiki to make it clear where you can find that. I didn't look at the Linux server page.

**Comment by gilgongo** [comment]
Hard to know how we might make it clearer. The use of siguser only relates to server operators running Linux headless, who (presumably) would consult the Linux headless server docs, where the operation of recording is described. I suppose we could link to it from Tips & Tricks, but where do you draw the line?

Server operators running Linux with the GUI, and all other OSes, don't need to know about the siguser method.

**Pull request merged**
