### PR TITLE
Make copyright file translatable

### LINKED ISSUE #796: [Translate] Some untranslatable strings.
# Language you want to translate to
All languages
# Description
"This documentation is CC BY-SA" is untranslatable. Please see the image below:
ccby

### PR DESCRIPTION
**Pull request by ignotus666**
**Short description of changes**
Makes copyright text translatable.

**Context: Fixes an issue? Related issues**
Fixes #796

**Status of this Pull Request**

**What is missing until this pull request can be merged?**

**Does this need translation?**

YES

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Comment by trebmuh** [comment]
Will that be made translatable through Weblate, or do you want me to submit a PR against the https://github.com/ignotus666/jamuluswebsite/tree/add-cw branch ?

**Comment by ignotus666** [comment]
Yes, it will turn up on Weblate.

**Comment by trebmuh** [comment]
OK, thanks for the quick answer.

**Comment by ann0see** [comment]
Thanks. Looks good. Let’s wait and see what Weblate does

**Pull request merged**
