### PR TITLE
[en] Update en-Linux-Install-Script.md

### PR DESCRIPTION
**Pull request by trebmuh**
A few improvements and typos spotted while doing the French translation of this page.

I've got a doubt about this sentence:

>[...] all the commands above into one script [...]

[There are no command "above"](https://jamulus.io/wiki/Linux-Client-Install-Script) so they're is something wrong. It might well be talking about either the commands in _**another page**_ or the commands _**below**_.

@gilgongo can you please have a look to it and advise? I'll add it to this PR then.

### CODE REVIEW

**Comment by gilgongo** [comment]
Ah, this was one of the contributions I was a bit worried about as I'd not been able to check it. 

The whole thing was originally simply pasted into the middle the Linux install page by somebody on the wiki. Rather than offend them by removing it, I put it into a separate document and linked it from the Linux install page. So that might explain the "above" thing. I'd sort of assumed that anyone in their right mind would not read it (it looks far too much trouble to actually do).

It looks likely that we can move it to the new "community" area for SEO food, and where I think it can be picked over by anyone who wants to. So, how about you just translate it as is, I'll remove the link to it from the English Linux install page, and we can deal with it later along with the other things for the community section?

**Review by gegeweb — APPROVED** [review]
Sounds good to me.

**Comment by trebmuh** [comment]
> So, how about you just translate it as is, I'll remove the link to it from the English Linux install page, and we can deal with it later along with the other things for the community section?

I assume that you talk about the "above" here. If so, I'm OK with that.
@gilgongo you can merge this PR then (the "above" is untouched) if you're fine with the other changes too.

**Comment by ann0see** [comment]
I think niebert should update it: https://github.com/niebert

**Comment by trebmuh** [comment]
@ann0see Is that the personn who wrote this first?

**Comment by gilgongo** [comment]
@trebmuh Yes. And we can't call him the Sonic Emperor, unfortunately.

**Comment by trebmuh** [comment]
@gilgongo I don't get what the meaning intended in your last sentence.
I've checked his github page and it seems to be active on github.
We could/should simply tag him here, isn't?

**Comment by trebmuh** [comment]
_(conflicting files resolved)_

**Comment by gilgongo** [comment]
Yes, we can tag him here.

**Comment by trebmuh** [comment]
Hi @niebert. We don't know each other yet, but it looks like you've been writing the original documentation that we're working on in this thread. Could you please help us here and suggest how we should reformulate this sentence we're talking about?

**Comment by ann0see** [comment]
@trebmuh Once you get push access (think we can give it to you tomorrow), you can add it to the blog branch. 

Note: you will not be able to push to the release branch without reviews and a pr.

**Comment by trebmuh** [comment]
@ann0see ok

By the way, before I'm starting to push, I'll ask you and/or @gilgongo to re-brief me about which branch is intended for what. They've been changing on those last day and I'd like to avoid to learn it "the hard way" as the saying goes.

**Comment by ann0see** [comment]
See https://github.com/jamulussoftware/jamuluswebsite/issues/31#issuecomment-735468060 (at least that's how I understand the process).

You can now push to changes probably translation (?) but not release.

**Comment by ann0see** [comment]
https://github.com/corrados/jamulus/issues/705#issuecomment-720050333

> Furthermore I want to ask you to remove the annotation "sonic emperor" from my name on the Web Site https://github.com/jamulussoftware/jamulussoftware.github.io/blob/main/wiki/en/en-Tips-Tricks-More.md - you can remove or improve my edits or use them or build on them if you think there are useful according to you quality assurance quidlines. My comments were good faith edits.

So I think @trebmuh you can improve and fix his edits.

**Comment by trebmuh** [comment]
@ann0see I'm fine to do so. You're OK with merging this as a [blog post](https://github.com/jamulussoftware/jamuluswebsite/pull/101) as [suggested be gilgongo](https://github.com/jamulussoftware/jamuluswebsite/pull/97#issuecomment-735250685) above IIUC?

**Comment by ann0see** [comment]
Yes. It should be in the new community section.

**Comment by niebert** [comment]
Excuse me for the late reply, the contribution was made to Volker Fischers repository. Please feel free to edit the script. Created that just as support for people that battle to put  all the required command lines in the Linux shell. At the same time I thought it might also be helpful for other OpenSource community  members that want to use Jamulus on Linux. I wrote that script for Volker Fischers repository have multi distro support in mind (Ubuntu, Mint, ...) and handle that in one script with a distro dependent call of install commands e.g. `apt-get` on Ubuntu. Furthermore specific distro and version specific dependent install command might be required, e.g. a version specific install command like `sudo apt-get lib-on-18.4` for Ubuntu 18.4 and `sudo apt-get lib-on-20.4` for Ubuntu 20.4 . With a shell script and `sed` or with NodeJS the distro and version specific install scripts can be generated within a build processed. That sets just the build variables for the distribution and version in the shell variable at the top of the script and users can just run the `jamulus-ubuntu-18-4-client-install.sh` or `jamulus-ubuntu-20-4-client-install.sh` without asking them about their Linux DIstro and the Linux Version. Anyway thank you all for supporting this great piece of software. Might create a small repository for my scripts and you can decide if they make sense to you to integrate them to the Jamulus repository for clients or servers.
Best regards,

**Comment by ann0see** [comment]
Great! Thanks for your reply!

@niebert do you want to do the changes or should @trebmuh do them? 

In my opinion @niebert, we should also discuss the Software Synth Page. (We should add pictures, a few clarifications etc.) should we open a PR on that? Edit: done: #170

**Comment by ann0see** [comment]
Edit: now a real reply to your answer (I now have a bit more time...) @niebert

> Might create a small repository for my scripts and you can decide if they make sense to you to integrate them to the Jamulus repository for clients or servers.

Yes, I think that's the best solution. 

We can link the scripts from the page with your descriptions? This allows you to make changes more easily. We can then restructure this page a bit and link to your repo.

> I wrote that script for Volker Fischers repository have multi distro support in mind (Ubuntu, Mint, ...) and handle that in one script with a distro dependent call of install commands e.g. apt-get on Ubuntu

Yes. That's a good idea (although the installation is not too difficult in my opinion). Also we have a few packages already available (but at least for Debian it will take some time)

> With a shell script and sed or with NodeJS the distro and version specific install scripts can be generated within a build processed.

Do you mean "build process"? Yes, I think it would be great if @corrados also compiled linux binaries. He can use these scripts (but will also need multiple distros on his device). I think we could also try building with a github action or travis cli. Please open an issue on the main repo for that.

**Comment by ann0see** [comment]
Closed in favour of #171

**Pull request closed without merging**
