### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Jamulus/Startpage](https://hosted.weblate.org/projects/jamulus/1-index/).

It also includes the following components:

* [Jamulus/Command-Line-Options](https://hosted.weblate.org/projects/jamulus/command-line-options/)

* [Jamulus/FAQ](https://hosted.weblate.org/projects/jamulus/faq/)

* [Jamulus/Installation-for-Windows](https://hosted.weblate.org/projects/jamulus/installation-for-windows/)

* [Jamulus/Unregistered-Servers](https://hosted.weblate.org/projects/jamulus/unregistered-servers/)

* [Jamulus/Navigation](https://hosted.weblate.org/projects/jamulus/navigation/)

* [Jamulus/Include-Client-Commands](https://hosted.weblate.org/projects/jamulus/include-client-commands/)

* [Jamulus/Software-Manual](https://hosted.weblate.org/projects/jamulus/software-manual/)

* [Jamulus/Privacy-Statement](https://hosted.weblate.org/projects/jamulus/privacy-statement/)

* [Jamulus/Include-Backing-Up](https://hosted.weblate.org/projects/jamulus/include-backing-up/)

* [Jamulus/Installation-for-iOS](https://hosted.weblate.org/projects/jamulus/installation-for-ios/)

* [Jamulus/Installation-for-Android](https://hosted.weblate.org/projects/jamulus/installation-for-android/)

* [Jamulus/Tips-Tricks-More](https://hosted.weblate.org/projects/jamulus/tips-tricks-more/)

* [Jamulus/Server-Troubleshooting](https://hosted.weblate.org/projects/jamulus/server-troubleshooting/)

* [Jamulus/Server-Bandwidth](https://hosted.weblate.org/projects/jamulus/server-bandwidth/)

* [Jamulus/Getting-Started](https://hosted.weblate.org/projects/jamulus/getting-started/)

* [Jamulus/Contribution](https://hosted.weblate.org/projects/jamulus/contribution/)

* [Jamulus/Include-Shared-Commands](https://hosted.weblate.org/projects/jamulus/include-shared-commands/)

* [Jamulus/Installation-for-Macintosh](https://hosted.weblate.org/projects/jamulus/installation-for-macintosh/)

* [Jamulus/QOS-Windows](https://hosted.weblate.org/projects/jamulus/qos-windows/)

* [Jamulus/Directories](https://hosted.weblate.org/projects/jamulus/directories/)

* [Jamulus/Copyright notices](https://hosted.weblate.org/projects/jamulus/copyright-notices/)

* [Jamulus/Client-Troubleshooting](https://hosted.weblate.org/projects/jamulus/client-troubleshooting/)

* [Jamulus/General strings](https://hosted.weblate.org/projects/jamulus/general/)

* [Jamulus/Running-a-Server](https://hosted.weblate.org/projects/jamulus/running-a-server/)

* [Jamulus/Installation-for-Linux](https://hosted.weblate.org/projects/jamulus/installation-for-linux/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by pljones** [comment]
Is there any reason _not_ to merge to `next-release`?  I mean, are there specific problems identified that are unresolved?

**Comment by ignotus666** [comment]
There are a bunch of links that need to be corrected (particularly in `th` and `sv-SE`, a consequence of MT), but it doesn't look like the original translators are going to fix them. I'd be in favour of merging this and sorting those out over time, and see if Weblate stops locking itself up - it's doing it every day.

**Comment by ignotus666** [comment]
I just fixed the `sv-SE` links (I think I got all of them). Since `th` isn't finished I can't do those yet.

**Comment by pljones** [comment]
OK, I'll merge this an we can fix any disasters later.

**Comment by ignotus666** [comment]
This should have been merged before #1060. I don't think the `th` conflicts here are directly related to that but it caused Weblate to lock up.

**Comment by pljones** [comment]
@ignotus666 @gilgongo 
Well, that seems to have fixed it for now.

I suggest before merging anything to `next-release`, we always:
- lock Weblate
- merge the Weblate changes to `next-release`
- make sure Weblate is happy
- merge the PR
- update Weblate
- make sure Weblate is happy
- unlock Weblate

Otherwise when we merge changes that cause it to drop out of sync, it's going to need the manual merge I just had to do to fix it up, I think.

**Comment by pljones** [comment]
Closing as Weblate now claims to be up to date.

**Pull request closed without merging**
