### PR TITLE
Update en-Sound-Devices.md

### PR DESCRIPTION
**Pull request by achim-grosse-oetringhaus**
Added Behringer XENYX 1832 USB

### CODE REVIEW

**Comment by ann0see** [comment]
Thanks! @gegeweb is currently restructuring this page (as far as I know #169)? Therefore I think it would be better to add it to his proposal first?

**Comment by gegeweb** [comment]
On #169 I mention the whole Xenix series.

**Comment by ann0see** [comment]
Ok @achim-grosse-oetringhaus @gegeweb so this will already be part of the new sound devices page?

**Comment by ann0see** [comment]
@achim-grosse-oetringhaus @gegeweb I will add this device as a comment to the new file.

**Comment by ann0see** [comment]
Just a fake merge here since it has been added to a different page.

**Pull request merged**
