### PR TITLE
Rename 'pt' .po folder to 'pt_PT' and update _config.yml

### PR DESCRIPTION
**Pull request by ignotus666**
**Short description of changes**
Having a language defined as just 'pt' in the website docs is causing Weblate to think we have 3 different Portuguese variants ('pt_BR', 'pt_PT' from the app repo, and 'pt').

**Context: Fixes an issue? Related issues**

**Status of this Pull Request**
Tested and working locally. Yet to be seen if Weblate combines pt and pt_PT but it should.

**What is missing until this pull request can be merged?**
Can't really know if it works until it's merged.

**Does this need translation?**

Yes - the language in the header for 'pt_PT' docs has to be changed from 'pt' to pt_PT'. I'd rather that was done on Weblate to avoid the risk of conflicts.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Comment by ignotus666** [comment]
The "zip website" step is failing... no idea why.

Error message: `zip warning: name not matched: _site/*`

**Comment by pljones** [comment]
> The "zip website" step is failing... no idea why.
> 
> Error message: `zip warning: name not matched: _site/*`

It's failing to create `_site/` files because of some change causing po4a to die in an earlier step.  The build should really halt on that error rather than continue to fail here.

**Comment by ignotus666** [comment]
Are you sure? I can't see where po4a died - it created the appropriate translated files and didn't complain about anything. It didn't run "Update .po files" because it's not supposed to as there were no changes to EN files.

**Comment by pljones** [comment]
In "Build the site in the jekyll/builder container", I see
```
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/usr/gem/gems/jekyll-4.2.2/lib/jekyll/utils.rb:141:in `initialize': No such file or directory @ rb_sysopen - /srv/jekyll/1-pt-index.html (Errno::ENOENT)/usr/gem/gems/jekyll-4.2.2/lib/jekyll/utils.rb:141:in `initialize': No such file or directory @ rb_sysopen - /srv/jekyll/1-pt-index.html (Errno::ENOENT)
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/utils.rb:141:in `open'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/utils.rb:141:in `has_yaml_header?'
```
It fails to go further for anything.  I don't know why that step declares success.

**Comment by ignotus666** [comment]
Thanks for the hint - I think I know what's going on.

**Comment by ignotus666** [comment]
Fixed. Turns out there was more to it than I thought.

**Comment by ignotus666** [comment]
I'm going to close this as conflicts have surfaced that will only increase in number as more changes are merged. I'll open a new PR once 3.9.1 is out.

**Pull request closed without merging**
