### PR TITLE
NL translation

### PR DESCRIPTION
**Pull request by henkdegroot**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

Initial Dutch translation added to next-release branch

Fixes: #646

### CODE REVIEW

**Comment by ignotus666** [comment]
Wow, that was quick, great work, I see you even created the screenshots! I've had a brief look at a local build of the website and it seems to be all ok - I don't speak a word of Dutch so can't comment on that, but all the formatting looks good and so do the links.

**Comment by henkdegroot** [comment]
Well to be honest, I did start translating a bit before I requested the new language as I wanted to make sure I could build locally to  check and verify. Also the process is documented well and easy to follow, so not much issue. The main issue I had was with some odd characters (like ë and ï) which OmegaT kept changing into double characters, hence the reason I moved to PoEdit.

**Comment by ignotus666** [comment]
> The main issue I had was with some odd characters (like ë and ï) which OmegaT kept changing into double characters

That's interesting, I was wondering why you'd made the switch. OmegaT is quite a mature and widely-used tool so I wonder if there is some configuration that needs to be done somewhere to properly display those characters. Spanish uses diaeresis on some letters but I never ran into problems.

Glad to hear you found the documentation easy to follow - you're the first person to start a translation from scratch with the "new" system, so any feedback is welcome :)

**Comment by henkdegroot** [comment]
The issues I had with OmegaT may have been caused by the fact that I use a virtual linux machine for this and copy files to/from my windows machine. I also did not realize that the "source" folder is not updated (or at least not always) with the translation but only the "target" folder. I used the editor to my first round of translation and then noticed the issues with these characters. This was all on the linux machine. Next I tried PoEdit and did not have any problem updating the incorrect characters. I did not want to spent more time on this and since PoEdit works fine, I will keep using that.

**Pull request merged**
