### PR TITLE
Updating images + labels

### PR DESCRIPTION
**Pull request by gilgongo**
# Does this need translation?

- [] Yes 
- [x] No 

# Changes

New screenshots to reflect last release. Changing "Onboarding" to "Setup". As per https://github.com/jamulussoftware/jamuluswebsite/issues/525

Other languages are up to date.

### CODE REVIEW

**Comment by ann0see** [comment]
wrong
Something is wrong here...

**Comment by gilgongo** [comment]
That's weird. Is that the same for the other images I updated? Also, how do you get this dark mode to work? Is that a brower setting?

**Comment by ann0see** [comment]
No. I don’t think so. Dark mode is a browser setting (which then applies specific CSS). In chrome you can set "prefers-color-scheme" manually.

**Comment by gilgongo** [comment]
OK the png had some strange alpha channel setting on it. Can you try again?

**Comment by ann0see** [comment]
Hmm. No. It still seems to be like that...

You can try to set dark mode via Chrome/-ium Dev Tools>Rendering> Emulate CSS media feature prefers-color-scheme>prefers-color-scheme: dark

**Comment by gilgongo** [comment]
OK I may have uploaded the same file again by mistake using the web UI. I've tried again from the CLUI.

**Comment by ignotus666** [comment]
Wouldn't it be better to separate out the image updates and make a PR for them to 'release'? That way they can go live now instead of waiting for the next release. ES (and I think FR) already have those images up to date.

**Comment by gilgongo** [comment]
Oh I didn't check if they were up to date on the other languages. So we could merge this OK to release then.

**Comment by ignotus666** [comment]
I was going to say that since it has to be translated, the Onboarding -> Setup change should go to 'next-release', but 'release' gets merged into 'next-release' once in a while, doesn't it? It'd make no difference for translations then.

**Comment by gilgongo** [comment]
Ah yes - now that po4a is in the house we can merge next-release into release whenever we want, is that right?

**Comment by ignotus666** [comment]
Yup, I can't think of a reason why not. Running po4a-update-templates.sh will sync the .po files to whatever state the EN wiki docs are in.

**Comment by jujudusud** [comment]
Be careful. Remember that "next release" allows you to collect all the changes before a release and that it allows you to trace the changes made in EN before translating...
I don't think it's a good idea to make changes that don't have to go into the online site right away in "release" because it doesn't allow you to make a small change in the site.

**Comment by gilgongo** [comment]
OK but in this case (for this PR) EN is actually more out of date than the other languages.  But I get what you mean about next-release.

BTW the checks seems to be taking ages in this...

**Comment by jujudusud** [comment]
This PR is part of small changes that have to be made and pushed  to the online site right away. ;-)

**Comment by ignotus666** [comment]
> allows you to collect all the changes before a release and that it allows you to trace the changes made in EN before translating

Is there a particular reason why we need to be able to trace all the changes made to EN docs in a single place (squash&merge?) ?

**Comment by jujudusud** [comment]
> 
> Is there a particular reason ...

Only to be sure that all the changes needed in the next release are done before translating. I personally think that it is safer/easyier to do this in one branch and not multiple branches as it has been done for 3.8.0 unfortunatly.

**Comment by ignotus666** [comment]
I think we need a separate branch from 'release' so that new/unfinished content doesn't go live straight away. AFAIK all content changes are being done to 'next-release'. 'Release' is only receiving corrections.

**Pull request merged**
