### PR TITLE
For 3.6.2 release 13th Dec

### PR DESCRIPTION
**Pull request by gilgongo**
Edit by @ann0see:

This PR includes the changes for the upcoming version of the Jamulus website. Please translate the changes.

### CODE REVIEW

**Comment by gilgongo** [comment]
Updates for translation.

**Comment by ann0see** [comment]
@jamulussoftware/translators 

These changes can be translated now. Submit your translations to the `translate` branch please.

Since we now have a lot more people contributing to the website, please follow these guidelines for this PR.

1. Issues not related to this PR should be raised in a separate issue. 

2. The discussion about this PR should focus on the current changes (if there is a typo for these specific changes which only affects the English version, you can comment on this pr). Also you can ask if you don't understand a specific English change. But if you don't like it, please search for/open a separate issue.

3. If something is only related to a specific language, please open an issue or pr to the translate branch and discuss the changes there with the other people of your translation team.

This keeps the discussion of this the PR tidy and focused.

**Comment by ignotus666** [comment]
Typo or missing text in "en-Contribution.md", line 23: "on" at the end of the line.

**Comment by ann0see** [comment]
fixed by removing on. Further discussion in #157

**Comment by trebmuh** [comment]
I'll do this in about 4 hours for the French translation.

**Comment by gegeweb** [comment]
@trebmuh 

> I'll do this in about 4 hours for the French translation.

I had worked on index page, I'm going to open a PR for this.

**Comment by ann0see** [comment]
Please discuss this in #38 

Trying to keep this PR focused (if this is needed/unneeded shall be discussed later on in #31)

**Pull request merged**
