### PR TITLE
Add --listfilter documentation

### PR DESCRIPTION
**Pull request by gilgongo**
Will also create link to this from Configuration page.

### CODE REVIEW

**Review by pljones — APPROVED** [review]
> "NAT" is misspelled. How about: ANT, TAN, NAT, BAT, MAT, NAY

Is that bot adding any value in suggesting replacing `NAT` with `NAT`..?

**Comment by gilgongo** [comment]
Hehe - I was about to ask the same. Seems a bit... buggy? _"'1' is misspelled. How about: 1"_ :-)

**Review by ann0see — APPROVED** [review]

**Comment by ann0see** [comment]
@hoffie could you please review this too?

**Review by hoffie — APPROVED** [review]
Sounds good :)

**Comment by ann0see** [comment]
Thanks!

**Pull request merged**
