### PR TITLE
WEBSITE RELEASE FOR 3.8.0

### PR DESCRIPTION
**Pull request by ann0see**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

Merging this PR will update the website to release 3.8.0. As soon as the website is finished, press the merge button and the site will go live.

### CODE REVIEW

**Comment by ann0see** [comment]
We're almost ready ...

**Comment by ann0see** [comment]
Fixed the last issue (missing PT screenshots)

**Comment by ann0see** [comment]
@gilgongo could you please cross check if the site is ready?

**Comment by gilgongo** [comment]
Looks ok (some links on the home page are opening in new windows for some reason but we can fix those later).

**Comment by ann0see** [comment]
Ok. So I'd say we can press the button now?

**Review by gilgongo — APPROVED** [review]

**Comment by ann0see** [comment]
Thanks. It's live now ;-)

**Pull request merged**
