### PR TITLE
Apply rexml upgrade again

### PR DESCRIPTION
**Pull request by ann0see**
Got another PR from dependabot which should be merged to next-release

### CODE REVIEW

**Comment by pljones** [comment]
Closing as duplicate of #1000

**Comment by ann0see** [comment]
The next-release branch needs to be updated.

**Comment by pljones** [comment]
Oh I see.  Is there anything blocking this happening?

**Comment by ann0see** [comment]
Yes. I think automation doesn’t work since we haven’t white listed some outdated dependencies. And there are conflicts here.

**Comment by ann0see** [comment]
Probably we‘ll just need to update the lock file locally on a PC. 
The site is ok despite the build error.

**Comment by ann0see** [comment]
Ok. Updated the lock file on PC. Will also need some update of the ruby version - but this should happen on next-release.

**Pull request merged**
