### PR TITLE
[fr] links fixes (fr-Server-Win-Mac.md)

### PR DESCRIPTION
**Pull request by trebmuh**
@ann0see : please commit ASAP

### CODE REVIEW

**Comment by ann0see** [comment]
Something seems to be wrong with the GitHub action.

**Comment by ann0see** [comment]
I will merge it but we might have problems. Let's take the risk (git allows us to go back if something fails)

**Review by ann0see — APPROVED** [review]
I hope this wasn't the wrong decision.

**Comment by ann0see** [comment]
Ok. This was just the CI.

**Comment by trebmuh** [comment]
Thank you very much @ann0see .

**Pull request merged**
