### PR TITLE
[Translate FR] add translated fr-Demos.md

### PR DESCRIPTION
**Pull request by jujudusud**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

add translated fr-Demos.md file.

### CODE REVIEW

**Comment by gilgongo** [comment]
Oh wait, I think these are merging to the wrong branch. They should be on the Release branch. Its only the English that goes to Changes. I'll switch that. 

EDIT: Actually, is this not supposed to be on a Translation branch for 3.8? @ann0see may be able to help...

**Comment by jujudusud** [comment]
Don't merge my commit 924931c on release while i is intended to be merged in changes.
The other translate fr are also intended to be merged to changes branch.

> EDIT: Actually, is this not supposed to be on a Translation branch for 3.8? @ann0see may be able to help...

Where is this "Translation branch for 3.8"? I'm unable to locate it in jamuluswebsite repository. There is only "changes".

**Comment by hoffie** [comment]
> Where is this "Translation branch for 3.8"? I'm unable to locate it in jamuluswebsite repository. There is only "changes".

There is none yet because the translation process hasn't been officially started yet as there may still be small documentation additions for 3.8. We will ping all translators once the freeze has been decided upon.

Maybe the best way forward would be to wait a couple of days until the branch has been created and then merge into this branch?

**Comment by jujudusud** [comment]
Ok for that.
Waiting for the new branch.

**Pull request closed without merging**
