### PR TITLE
Update deprecated actions

### PR DESCRIPTION
**Pull request by ignotus666**
**Short description of changes**
Actions haven't been updated for some time and some versions are close to being unsupported.

**Context: Fixes an issue? Related issues**

**Status of this Pull Request**
2nd attempt - should be ready; tested and working on my fork.

**What is missing until this pull request can be merged?**

**Does this need translation?**

No.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Comment by ignotus666** [comment]
When testing the website artifact created by the gh action, the gemfile isn't there, leading to an error. If I manually paste it into the folder, it works fine. I don't really know much about this stuff... @ann0see any ideas?

**Comment by ignotus666** [comment]
Testing on a clone of my fork the website works fine, so something's happening in the gh action creating the artifact.

**Comment by ann0see** [comment]
Thank you very much. That's odd. Does jekyll update create it?

**Comment by ann0see** [comment]
I mean: the artifact is the compiled website, I think. So it doesn't have the gemfile. But the repo should.

**Comment by ignotus666** [comment]
@ann0see Huh... I just downloaded it again and tried it with the command `jekyll serve` (instead of `bundle exec jekyll serve`) and it worked. So it was just a case of me getting my commands mixed up...

**Review by ann0see — APPROVED** [review]

**Pull request merged**
