### PR TITLE
Update - it

### PR DESCRIPTION
**Pull request by dzpex**
Sorry but i had many problem and my time is very poor. But I continue to translate!

### CODE REVIEW

**Comment by ann0see** [comment]
No problem ;-). Please use the translate branch or release for reference! changes is not the version to be translated (yet).

Thank you very much for your work!

**Comment by ann0see** [comment]
@dzpex A lot has changed in the last few months (primarily since we now have quite some languages which have to be in sync). That's why the translation process has changed a bit. 

Mainly for you it means that we will be merging your translation to "release" and if you'd like to change something in the English translation, you should open a PR to the changes branch to allow other translators to integrate your changes. Only English should be changed on "changes", "release" is what's going online and "translate" is only active if you participate in the official "translation cycle" which we will start about one week before corrados makes a new release of Jamulus.

I hope this makes sense to you. If you need help, just ask ;-)

**Comment by dzpex** [comment]
Ok i will use "release" and no change....for the PR its correct?

**Comment by ann0see** [comment]
I already added it manually:

3e84caf

So the change goes live.

**Comment by ann0see** [comment]
Just open a pr to release for other Italian translations. 

Thanks again for your work.

And the next translations should be based on what is on release. Also the PRs should go to release

**Comment by dzpex** [comment]
Its ok thanks very much

**Comment by ann0see** [comment]
No problem. Sorry for my confusing answer and all the changes in the translation process.

**Pull request closed without merging**
