### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Jamulus/Startpage](https://hosted.weblate.org/projects/jamulus/1-index/).

It also includes the following components:

* [Jamulus/Running-a-Server](https://hosted.weblate.org/projects/jamulus/running-a-server/)

* [Jamulus/Command-Line-Options](https://hosted.weblate.org/projects/jamulus/command-line-options/)

* [Jamulus/Unregistered-Servers](https://hosted.weblate.org/projects/jamulus/unregistered-servers/)

* [Jamulus/Installation-for-Android](https://hosted.weblate.org/projects/jamulus/installation-for-android/)

* [Jamulus/Navigation](https://hosted.weblate.org/projects/jamulus/navigation/)

* [Jamulus/Installation-for-iOS](https://hosted.weblate.org/projects/jamulus/installation-for-ios/)

* [Jamulus/Copyright notices](https://hosted.weblate.org/projects/jamulus/copyright-notices/)

* [Jamulus/Include-Backing-Up](https://hosted.weblate.org/projects/jamulus/include-backing-up/)

* [Jamulus/Tips-Tricks-More](https://hosted.weblate.org/projects/jamulus/tips-tricks-more/)

* [Jamulus/Server-Troubleshooting](https://hosted.weblate.org/projects/jamulus/server-troubleshooting/)

* [Jamulus/Client-Troubleshooting](https://hosted.weblate.org/projects/jamulus/client-troubleshooting/)

* [Jamulus/Installation-for-Macintosh](https://hosted.weblate.org/projects/jamulus/installation-for-macintosh/)

* [Jamulus/Include-Shared-Commands](https://hosted.weblate.org/projects/jamulus/include-shared-commands/)

* [Jamulus/Software-Manual](https://hosted.weblate.org/projects/jamulus/software-manual/)

* [Jamulus/QOS-Windows](https://hosted.weblate.org/projects/jamulus/qos-windows/)

* [Jamulus/Include-Client-Commands](https://hosted.weblate.org/projects/jamulus/include-client-commands/)

* [Jamulus/General strings](https://hosted.weblate.org/projects/jamulus/general/)

* [Jamulus/Contribution](https://hosted.weblate.org/projects/jamulus/contribution/)

* [Jamulus/Server-Bandwidth](https://hosted.weblate.org/projects/jamulus/server-bandwidth/)

* [Jamulus/Getting-Started](https://hosted.weblate.org/projects/jamulus/getting-started/)

* [Jamulus/FAQ](https://hosted.weblate.org/projects/jamulus/faq/)

* [Jamulus/Installation-for-Linux](https://hosted.weblate.org/projects/jamulus/installation-for-linux/)

* [Jamulus/Installation-for-Windows](https://hosted.weblate.org/projects/jamulus/installation-for-windows/)

* [Jamulus/Directories](https://hosted.weblate.org/projects/jamulus/directories/)

* [Jamulus/Privacy-Statement](https://hosted.weblate.org/projects/jamulus/privacy-statement/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by pljones** [comment]
Checking this one, too, as it's definitely a different file:
*English* `_site/wiki/Installation-for-Linux.html`
```
<link rel="canonical" hreflang="en" href="/wiki/Installation-for-Linux">
<link rel="alternate" hreflang="sv-SE" href="/sv-SE/wiki/Installation-for-Linux">
```
*Swedish* `_site/sv-SE/wiki/Installation-for-Linux.html`
```
<link rel="canonical" hreflang="en" href="/sv-SE/wiki/Installation-for-Linux">
<link rel="alternate" hreflang="sv-SE" href="/sv-SE/wiki/Installation-for-Linux">
```

**Comment by gilgongo** [comment]
In an earlier commit in my PR, I originally had:

`<link rel="canonical" hreflang="en" href="{{ site.url }}{{ page.url }}">`

But we [changed it here](https://github.com/jamulussoftware/jamuluswebsite/pull/1026#discussion_r1730326315). Is that perhaps implicated in what's going on?

**Comment by pljones** [comment]
> In an earlier commit in my PR, I originally had:
> 
> `<link rel="canonical" hreflang="en" href="{{ site.url }}{{ page.url }}">`
> 
> But we [changed it here](https://github.com/jamulussoftware/jamuluswebsite/pull/1026#discussion_r1730326315). Is that perhaps implicated in what's going on?

I guess it's related somehow...

**Comment by gilgongo** [comment]
What if I do a PR to test what happens if I put it back to `<link rel="canonical" hreflang="en" href="{{ site.url }}{{ page.url }}">`? At the moment we can't know whether the local version or the GH zip will be the one that comes out on release.

**Comment by ann0see** [comment]
May need a rebase...

**Comment by pljones** [comment]
Hit with a hammer.  Now fixed.

**Comment by ann0see** [comment]
Are the translations gone?

**Comment by pljones** [comment]
There were no new translations - they'd been merged successfully.  This was a fix to the build system:
https://github.com/jamulussoftware/jamuluswebsite/commit/9a045b384b890be57f2b212670d413def7402943
Weblate got confused, though, so I just told it to take what it was given from our side.  So now there's no changes and this can be closed, I guess.

**Comment by ann0see** [comment]
Are you sure? I thought there were translations

**Comment by pljones** [comment]
When do you think the translations happened, relative to the commits?
```
*   25400f1c 2024-09-22 (HEAD -> next-release, weblate/next-release, origin/release, origin/next-release, origin/HEAD, release) Merge pull request #1041 from jamulussoftware/dependabot/bundler/google-protobuf-4.28.2 [ann0see]
|\
| * a5455c34 2024-09-21 Bump google-protobuf from 4.28.0 to 4.28.2 [dependabot[bot]]
* | 07585e33 2024-09-22 Add .weblate link to Weblate translations [Peter L Jones]
* | 2b00ac8b 2024-09-21 Update ruby to 3.2.3 for builder [Peter L Jones]
|/
* 8a22b9cb 2024-09-21 RELEASE 3.11.0 (WEBSITE) (#1003) [ann0see]
* 628943e6 2024-08-05 Fix add-lang script 2 (#1021) [ignotus]
```

**Comment by ann0see** [comment]
https://github.com/jamulussoftware/jamuluswebsite/compare/503bdc9218632ac10c5b53f6637c5def74f30a8e..9a045b384b890be57f2b212670d413def7402943#diff-6bfc7b6a323989b18ef5ccb35a90eb634b54cb760b54feb08c258288ab14dd19L89
But this cold also have been a recreation of the po files. This text got removed.

**Comment by pljones** [comment]
So 9a045b38 is ahead of HEAD on next-release?  That I have the ref locally means I guess I dropped it at some point.
```
$ git log --graph 8a22b9cb~...9a045b384b8
*   9a045b38 2024-09-22 Merge release into next-release [github-actions[bot]]
|\
| * 25400f1c 2024-09-22 (HEAD -> next-release, weblate/next-release, origin/release, origin/next-release, origin/HEAD, release) Merge pull request #1041 from jamulussoftware/dependabot/bundler/google-protobuf-4.28.2 [ann0see]
|/|
| * a5455c34 2024-09-21 Bump google-protobuf from 4.28.0 to 4.28.2 [dependabot[bot]]
* | 07585e33 2024-09-22 Add .weblate link to Weblate translations [Peter L Jones]
* | 2b00ac8b 2024-09-21 Update ruby to 3.2.3 for builder [Peter L Jones]
|/
* 8a22b9cb 2024-09-21 RELEASE 3.11.0 (WEBSITE) (#1003) [ann0see]
```
However, `git diff 25400f1c..9a045b38` is empty for me...  I don't have 503bdc921 locally, though - so it never made it into my working copy.

**Comment by pljones** [comment]
Three dot diff:
https://github.com/jamulussoftware/jamuluswebsite/compare/503bdc9218632ac10c5b53f6637c5def74f30a8e...9a045b384b890be57f2b212670d413def7402943#diff-6bfc7b6a323989b18ef5ccb35a90eb634b54cb760b54feb08c258288ab14dd19L89

**Comment by pljones** [comment]
> The "exists" subcommand checks whether a ref has a reflog. It exits with zero status if the reflog exists, and non-zero status if it does not.

First, check locally to see if I have them...
```
find .git -name \*5b53f6637c5def74f30a8e -ls
```
Nope.
```
find .git -name \*2b212670d413def7402943 -ls
  4066198      4 -r--r--r--   1 peter    peter         879 Sep 22 18:03 .git/objects/9a/045b384b890be57f2b212670d413def7402943
```
Yep.

Now see if `git reflog` thinks they exist (0 = yes):
```
git reflog exists HEAD; echo $?
0
git reflog exists 503bdc9218632ac10c5b53f6637c5def74f30a8e; echo $?
1
git reflog exists 9a045b384b890be57f2b212670d413def7402943; echo $?
1
```
Hm.  So I can `git log HEAD~...9a045b384` and see the ref, but it doesn't exist, apparently.  Weird.

And if I create a branch at 9a045b384 and rebase to next-release, I get (as expected, given the diff) a no-op and the branch resets to next-release, losing the ref.

**Comment by pljones** [comment]
> 2 parents 07585e3 + 25400f1 = commit 9a045b3

```
git log --graph 07585e3~...release
*   25400f1c 2024-09-22 (HEAD -> release, weblate/next-release, origin/release, origin/next-release, origin/HEAD, next-release) Merge pull request #1041 from jamulussoftware/dependabot/bundler/google-protobuf-4.28.2 [ann0see]
|\
| * a5455c34 2024-09-21 Bump google-protobuf from 4.28.0 to 4.28.2 [dependabot[bot]]
* 07585e33 2024-09-22 Add .weblate link to Weblate translations [Peter L Jones]
```

Is 9a045b3 just trying to repeat commit 07585e3 (which was a squash)?

**Comment by pljones** [comment]
From what I can see from https://github.com/jamulussoftware/jamuluswebsite/compare/503bdc9218632ac10c5b53f6637c5def74f30a8e...release it looks like 503bdc9218632ac10c5b53f6637c5def74f30a8e is old - possibly around 3.10.0 time.

What I don't understand is why https://github.com/jamulussoftware/jamuluswebsite/commit/503bdc9218632ac10c5b53f6637c5def74f30a8e thinks it's parent is 257dbc8f8c1d9eb466e98c80365bb584a7965ecf:
```
 git log --graph 257dbc8~...
*   25400f1c 2024-09-22 (HEAD -> release, origin/release, origin/next-release, origin/HEAD) Merge pull request #1041 from jamulussoftware/dependabot/bundler/google-protobuf-4.28.2 [ann0see]
|\
| * a5455c34 2024-09-21 Bump google-protobuf from 4.28.0 to 4.28.2 [dependabot[bot]]
* | 07585e33 2024-09-22 Add .weblate link to Weblate translations [Peter L Jones]
* | 2b00ac8b 2024-09-21 Update ruby to 3.2.3 for builder [Peter L Jones]
|/
* 8a22b9cb 2024-09-21 RELEASE 3.11.0 (WEBSITE) (#1003) [ann0see]
*   4b5172fb 2024-09-02 Merge pull request #1032 from weblate/weblate-jamulus-1-index [ann0see]
|\
| * 11afd8d8 2024-09-01 Update Portuguese (Portugal) translation using Weblate [Hosted Weblate]
| * 2be881e5 2024-09-01 Update Swedish translation using Weblate [Hosted Weblate]
| * 1ca14040 2024-09-01 Update Dutch translation using Weblate [Hosted Weblate]
| * 2202e440 2024-09-01 Update German translation using Weblate [Hosted Weblate]
|/
* ae95abd2 2024-09-01 AUTO: Updated .po files [github-actions]
*   38012b1d 2024-09-01 Merge pull request #1031 from jamulussoftware/macOS/changeBundleId [ann0see]
|\
| * df6a8b6c 2024-09-01 Replace bundle id [ann0see]
|/
*   84f82de3 2024-09-01 Merge pull request #1019 from weblate/weblate-jamulus-1-index [ann0see]
|\
| * 7cc91e64 2024-08-30 Update translation files [Hosted Weblate]
| * 8bbf0cb2 2024-08-30 Update Chinese (Simplified) translation using Weblate [Hosted Weblate]
| * 4eec6f0c 2024-08-30 Update translation files [Hosted Weblate]
| * b6d08d2a 2024-08-30 Update translation files [Hosted Weblate]
| * 0ed879c3 2024-08-30 Update Swedish translation using Weblate [Hosted Weblate]
| * 6bd9e1a9 2024-08-30 Update translation files [Hosted Weblate]
| * 44d1f147 2024-08-30 Update Spanish translation using Weblate [Hosted Weblate]
| * ed079049 2024-08-30 Update Dutch translation using Weblate [Hosted Weblate]
| * e48abf07 2024-08-30 Update Italian translation using Weblate [Hosted Weblate]
| * e7060538 2024-08-30 Update translation files [Hosted Weblate]
| * 8431d2a9 2024-08-30 Update translation files [Hosted Weblate]
|/
*   b2a7a758 2024-08-06 Merge pull request #1023 from henkdegroot/update-3-11-screenshots [ann0see]
|\
| * 692106d8 2024-08-06 update-nl-images-for-3-11 [Henk De Groot]
|/
* a4c2a963 2024-08-05 AUTO: Add new language: sv-SE: Svenska #1022 [github-actions]
* a4f67868 2024-08-05 Revert "AUTO: Add new language: sv: Svenska #999" [ignotus666]
* 1eb8e580 2024-08-05 AUTO: Add new language: sv: Svenska #999 [github-actions]
* 0bfb3dcc 2024-08-05 Merge release into next-release [github-actions[bot]]
* 8b7f0dc8 2024-08-05 Merge release into next-release [github-actions[bot]]
* 4423ca4e 2024-08-04 Update dependencies [ann0see]
* 4cb6e572 2024-08-04 Fix syntax error [ann0see]
* ae814824 2024-08-04 AUTO: Updated .po files [github-actions]
*   919a1633 2024-08-04 Merge pull request #1007 from pljones/issue-1002-delete-server-button-docs [ann0see]
|\
| * 7556a29a 2024-08-02 Fix "My Profile" screenshot border [Peter L Jones]
| * cee15b2d 2024-07-30 Add note about delete button [Peter L Jones]
| * 9589b479 2024-07-30 Expand description of server list and say "directory" [Peter L Jones]
| * f2c2c6b1 2024-07-30 Mention connect via menu does not force disconnect [Peter L Jones]
|/
*   1f810469 2024-07-29 Merge pull request #1006 from ignotus666/upd_scrnshts [ann0see]
|\
| * 4fd1a9a3 2024-07-29 Add connection setup and advanced setup screenshots in ES [ignotus666]
* |   4b5761cb 2024-07-29 Merge pull request #1004 from ann0see/screenshots/addScreenshotUpdates [ann0see]
|\ \
| |/
|/|
| * e3b2b67b 2024-07-28 Add connection setup and advanced setup screenshots [ann0see]
* | 09c98b05 2024-07-28 Merge release into next-release [github-actions[bot]]
|/
*   1dd55421 2024-07-28 Merge pull request #1001 from jamulussoftware/release [ann0see]
|\
| * a3a19d1b 2024-07-28 Update dependencies [ann0see]
| *   b13603bb 2024-07-28 Merge branch 'next-release' into release [ann0see]
| |\
| |/
|/|
* |   faada8c0 2024-07-27 Merge pull request #998 from ignotus666/fix_lang_codes [ann0see]
|\ \
| * | bf2f931f 2024-07-27 Change po folders to new lang codes [ignotus666]
|/ /
* |   57c5f5ac 2024-07-27 Merge pull request #997 from jamulussoftware/release-update [ann0see]
|\ \
| * | 58f15542 2024-07-26 Merge branch 'next-release' into release-update [ann0see]
|/ /
* |   247363bf 2024-07-26 Merge pull request #994 from ignotus666/lang-select2 [ann0see]
|\ \
| * | 03646acb 2024-07-26 Update _includes/headtags.html [ignotus]
| * | 88c17bbf 2024-07-25 Tidy up and fix non-selectable EN [ignotus666]
| * | 98766c24 2024-07-24 Make current language non-selectable in non-JS mode [ignotus666]
| * | 5e0fda6a 2024-07-16 Fix canonical/alternate links [ignotus666]
| * | 6d642e93 2024-07-15 Fix canonical/alternate links [ignotus666]
| * | 5d837794 2024-07-10 Correct translation readme [ignotus666]
| * | 15510fd0 2024-07-03 Add language-container to fw.css [ignotus666]
| * | 0178a3b3 2024-07-02 Make non-JS selection highlighted [ignotus666]
| * | 45276967 2024-07-02 Correction to no-JS list [ignotus666]
| * | aade0e07 2024-07-02 Add no-JS option [ignotus666]
| * |   511d4f70 2024-07-01 Merge branch 'lang-select2' of https://github.com/ignotus666/jamuluswebsite into lang-select2 [Ignotus]
| |\ \
| | * | bb86c3cf 2024-07-01 Make dropdown standard html [ignotus666]
| | * | 8330b98a 2024-06-28 Make dropdown menu more compact [ignotus666]
| | * | 18b4a9bd 2024-06-27 Match text colour [ignotus666]
| | * | e4691dec 2024-06-27 Improve accessibility [ignotus666]
| | * | 13f90244 2024-06-26 Change add-lang message, remove suglang reference [ignotus666]
| | * | 0c930bba 2024-06-26 Replace with simplified version [ignotus666]
| * | | f7606cb8 2024-07-01 Replace with simplified version [Ignotus]
| |/ /
| * | 18a7af9f 2024-06-21 Lang select (#11) [ignotus]
* | |   a419206e 2024-07-23 Merge pull request #996 from softins/obsoleted-lrelease-and-qm [Tony Mountifield]
|\ \ \
| * | | 82da4926 2024-07-23 Update Release-Process.md [Tony Mountifield]
| * | | 654c317d 2024-07-23 Removed lrelease and .qm files check-in from release process. [Tony Mountifield]
* | | | 859e3aa8 2024-07-23 AUTO: Updated .po files [github-actions]
* | | |   c270fd21 2024-07-23 Merge pull request #989 from jamulussoftware/homepage-img [ann0see]
|\ \ \ \
| * | | | b42d18cd 2024-07-21 Better class name [Jonathan]
| * | | | b6535eb0 2024-07-21 Better class name [Jonathan]
| * | | | a9a9d9ad 2024-07-17 Add class for home page img [Jonathan]
| * | | | d816672b 2024-07-17 Use class for figure [Jonathan]
| * | | | a7198ef9 2024-06-06 Add figure style [Jonathan]
| * | | | ba7f8a40 2024-06-06 Replace banner image [Jonathan]
| | |/ /
| |/| |
* | | |   384118db 2024-07-23 Merge pull request #982 from jamulussoftware/update-ios-doc [ann0see]
|\ \ \ \
| |_|/ /
|/| | |
| * | | c484a7fc 2024-07-15 Rephrase sentence [ann0see]
| * | | ecbf3981 2024-02-27 Apply suggestion [ann0see]
| * | | b154f7d9 2024-02-01 Add changes to iOS install page [ann0see]
* | | |   9cccaad1 2024-07-15 Merge pull request #991 from weblate/weblate-jamulus-1-index [ann0see]
|\ \ \ \
| |_|/ /
|/| | |
| * | | 2124539b 2024-07-13 Update translation files [Hosted Weblate]
| * | | 18716905 2024-07-13 Update translation files [Hosted Weblate]
| * | | 4efabfbd 2024-07-13 Update translation files [Hosted Weblate]
| * | | acc5198c 2024-07-13 Update translation files [Hosted Weblate]
|/ / /
* | |   3d4db9c2 2024-04-26 Merge pull request #984 from ignotus666/dep-actions [ann0see]
|\ \ \
| * | | 2047600d 2024-04-18 Update deprecated actions [ignotus666]
|/ / /
* | | 12387957 2024-02-10 AUTO: Updated .po files [github-actions]
* | | a087bfda 2024-02-10 Update Installation-for-Linux.md adding PipeWire usage. (#980) [Julien Taverna]
* | | 04a0f589 2024-02-04 Translations update from Hosted Weblate (#978) [Weblate (bot)]
|/ /
* | b2ee5a32 2023-12-26 Merge release into next-release [github-actions[bot]]
* | f80d8c7a 2023-12-01 AUTO: Updated .po files [github-actions]
* | 25b09acb 2023-12-01 Fix segmentation in 1-Index 2nd attempt (#976) [ignotus]
* | b1ad370e 2023-12-01 Translations update from Hosted Weblate (#975) [Weblate (bot)]
* | 9ddd9974 2023-12-01 Revert "Fix segmentation in 1-Index (#970)" [Ignotus]
* | 8e938851 2023-12-01 Revert "AUTO: Updated .po files" [Ignotus]
* | a73218ec 2023-11-22 AUTO: Updated .po files [github-actions]
* | 256a6789 2023-11-22 Fix segmentation in 1-Index (#970) [ignotus]
* | ed744f42 2023-11-22 AUTO: Updated .po files [github-actions]
* | 58c5cec4 2023-11-22 Change jamulus-server to jamulus-headless (#969) [ann0see]
* | 26939ec2 2023-11-01 AUTO: Updated .po files [github-actions]
* | 62b4e762 2023-11-01 Use newlines for code to help with copy-paste (#968) [John Dempsey]
* | 68200341 2023-09-13 Merge release into next-release [github-actions[bot]]
* | b3ac6869 2023-09-12 Merge release into next-release [github-actions[bot]]
* | a9b58b40 2023-09-03 Merge release into next-release [github-actions[bot]]
* | 2b2668cc 2023-09-03 Merge release into next-release [github-actions[bot]]
 /
* 5cda24d1 2024-07-27 Merge pull request #1000 from jamulussoftware/dependabot/bundler/rexml-3.3.2 [ann0see]
* dca28ae8 2024-07-27 Bump rexml from 3.2.8 to 3.3.2 [dependabot[bot]]
```

**Comment by ann0see** [comment]
I just forced an update on weblate and a new translation showed up. 
I don't think it's the one I thought which was missing.

**Comment by pljones** [comment]
OK, as per https://github.com/jamulussoftware/jamuluswebsite/pull/1051 I'll merge this as it stands and let Weblate raise a new PR.

**Comment by pljones** [comment]
Well, it didn't blow up because of Gemfile.lock, at least.
```
Bundler 2.3.25 is running, but your lockfile was generated with 2.5.18. Installing Bundler 2.5.18 and restarting using that version.
```

```
   Conversion error: Jekyll::Converters::Markdown encountered an error while converting 'wiki/en/Running-a-Server.md':
                    No such file or directory @ rb_sysopen - /srv/jekyll/.jekyll-cache/Jekyll/Cache/Jekyll--Converters--Markdown/1c/704ed44ac671aff7b87f30d7acbcbce47ed2a5fc842a3136353f50a5a40ffb
```

**Comment by pljones** [comment]
I've tried deleting the cache and rerunning...

----

... which appears to have fixed it.
https://github.com/jamulussoftware/jamuluswebsite/actions/runs/11191720626

**Pull request merged**
