### PR TITLE
[Translate FR] add translated fr-Choosing-a-Server-Type.md

### PR DESCRIPTION
**Pull request by jujudusud**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

Adding fr-Choosing-a-Server-Type.md file.

### CODE REVIEW

**Comment by jujudusud** [comment]
Great !
Thanks.

**Comment by gilgongo** [comment]
@jujudusud Sorry about this but I realise I've been merging these to the wrong branch. I'm going to revert them for now. Can you add them again once we have set up the "Translation" branch for the 3.8.0 release?

**Comment by jujudusud** [comment]
It's been a long time since there is no translation of version 3.7.0 in French of the whole documentation and I would like it to be operational as soon as possible. 
Where do I have to merge the files so that they are integrated in the current website? I will translate the files from the same branch and PR.
After that I will help the French translators to update the next version whether it is called 3.7.1 or 3.8.0.

**Comment by gilgongo** [comment]
We've not yet finished all the English yet. But when we have, we'll create a Translation branch. You can then merge your translations into that branch. When all translations have merged into that, we merge to Release and it goes live. Sorry for the confusion.

**Comment by jujudusud** [comment]
Ok, waiting for the new translation branch. Thanks.

**Pull request merged**
