### PR TITLE
Update French translation for 3.8.0

### LINKED ISSUE #458: Update fr web translation for 3.8.0
Hi @jujudusud, @trebmuh,

We are getting ready for the 3.8.0 release and have created the [translate3_8_0](https://github.com/jamulussoftware/jamuluswebsite/tree/translate3_8_0) branch ([full diff](https://github.com/jamulussoftware/jamuluswebsite/compare/release..translate3_8_0)).

Because the English is still going through large changes, we are not expecting translations of anything other than the following pages:

- [Home page](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/1-index.html)
- [Setup](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Setup.md) (renamed from Getting-Started)
- Installation pages for each supported platform ([Windows](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Windows.md), [Mac](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Macintosh.md), [Linux](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Linux.md))

While you are of course welcome to translate more than this, please be aware that you may have to re-translate for the next release.

We would be happy if you updated the translations for **fr** until **2021-05-15**.

Please

- Start your work in your fork on a branch based on jamuluswebsite's `translate3_8_0` branch.
- Update the language-specific files using your favorite editor (or directly on Github),
- Commit and push your changes to your fork,
- Open a Pull Request with your translations to the **translate3_8_0** branch with the subject `Update fr web translation for 3.8.0`,
- Link your PR(s) to this issue by including `Fixes #458` in the PR content.

Note: The term "Central server" has been replaced with "Directory server"

This Issue is assigned to multiple people. Please coordinate who will translate what part.

Suggested commit and PR message:
```
Update fr web translation for 3.8.0

Fixes #458
```

Feel free to use this Issue to discuss anything you need prior to making any PR (and in your native language if needed).

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/README.md#translating).

Thanks for contributing to Jamulus!

### PR DESCRIPTION
**Pull request by jujudusud**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

Fixes #458

### CODE REVIEW

**Comment by hoffie** [comment]
@jujudusud I see that you are working on even more translations -- impressive! :)
I have converted your PR to a draft so that noone merges by accident before you are done. Please mark it as ready when you are. :)

**Comment by jujudusud** [comment]
Thanks a lot @hoffie 
Yes it is a draft for now ! :-)
Will let the team know when it is ready.

**Review by gilgongo — APPROVED** [review]
Looks good to me! Thanks!

**Comment by jujudusud** [comment]
Ready to be merged

**Pull request merged**
