### PR TITLE
Update Server-Troubleshooting.md

### PR DESCRIPTION
**Pull request by mightymatth**
**Short description of changes**

As I've recognized my own section is badly written, here are some corrections.

**Context: Fixes an issue? Related issues**

**Status of this Pull Request**

**What is missing until this pull request can be merged?**

**Does this need translation?**

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Comment by ignotus666** [comment]
Wouldn't it be better to switch the PR origin fork to `next-release` too? It'd get rid of the conflicts.

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
@mightymatth @ignotus666 yes it would be better to have the conflicts fixed - best case would be a git rebase. However since that's the website repo, I think we should just fix the conflicts by hand.

**Comment by gilgongo** [comment]
Looks good to me.

**Comment by ignotus666** [comment]
Oh, seems to be fixed, nice.

**Review by ignotus666 — APPROVED** [review]

**Pull request merged**
