### PR TITLE
Dzpex patch 1

### PR DESCRIPTION
**Pull request by dzpex**

### CODE REVIEW

**Comment by pljones** [comment]
What does this do?  The title says nothing.  The description says nothing.  It's huge.

**Comment by ann0see** [comment]
I assume this is a wrong PR. dzpex probably wants to update his own repo so that he can work on the italian translation?

**Comment by ann0see** [comment]
Ah. No it's about b43de03 he updated the footer.

**Comment by ann0see** [comment]
Ok. So it seems to be ok now. I'll merge this to changes and afterwards cherry pick b43de03

**Comment by dzpex** [comment]
sorry for my wrong PR yes i've updated the footer...i reload it from my branch

**Pull request merged**
