### PR TITLE
New Page

### PR DESCRIPTION
**Pull request by dzpex**

### CODE REVIEW

**Review by ann0see — CHANGES_REQUESTED** [review]
Hi! Thanks for these changes. The English doc (on the Linux install page) has now set the commands in  code blocks (start with 3 backticks) could you please add this change too?

**Comment by dzpex** [comment]
yes i provide.

**Comment by dzpex** [comment]
ok i've applied the change requested!

**Review by ann0see — APPROVED** [review]
Great!

I will merge it.

**Pull request merged**
