### PR TITLE
Replace screen shots for self-labelled checkboxes

### LINKED ISSUE #816: Checkbox controls should be "self-labelling"
Following up on https://github.com/jamulussoftware/jamulus/issues/2723#issuecomment-1239293096 so it doesn't get lost.

That issue has initial screenshots.  Once they're agreed, I'll post the final ones here along with any further changes needed in the "Software Manual" and "Running a Server" pages.

### PR DESCRIPTION
**Pull request by pljones**
**Short description of changes**

Updated screenshots to include the self-labelled checkbox changes.

**Context: Fixes an issue? Related issues**

Doc Issue: #816 
Code Issue: https://github.com/jamulussoftware/jamulus/issues/2723
Code Fix: https://github.com/jamulussoftware/jamulus/pull/2847

**Status of this Pull Request**

Awaiting build so I can check it.

**What is missing until this pull request can be merged?**

Review.  See http://jamuluswebsite.drealm.info/ for what it looks like.

**Does this need translation?**

YES

## Checklist
- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch ("**next-release**" *not* "release")

### CODE REVIEW

**Comment by ann0see** [comment]
@pljones Could you please rebase this PR

**Comment by ann0see** [comment]
Or maybe even re-do it manually due to the rebase on next-release

**Comment by pljones** [comment]
I'll re-do it once https://github.com/jamulussoftware/jamulus/pull/2847 gets finalised.

**Comment by ann0see** [comment]
@pljones this needs a rebase

**Comment by pljones** [comment]
It needs redoing once the code is finalised.

**Pull request closed without merging**
