### PR TITLE
1049 Fix JSON header layout

### LINKED ISSUE #1049: [Bug] Unparsable json in headers
Probably a minor issue, but Google is complaining that [https://jamulus.io/kb/2020/03/28/Server-Rpi.html ](https://jamulus.io/kb/2020/03/28/Server-Rpi.html) and [https://jamulus.io/it/kb/2022/08/04/Translating-po-files.html](https://jamulus.io/it/kb/2022/08/04/Translating-po-files.html) have  "Error parsing an array value: missing a comma or closing bracket in an array declaration."

```
  {
    "@context":"https://schema.org",
    "@type":"BlogPosting",
    "headline": "Install Jamulus Server on a Raspberry Pi",
    
    
    "publisher": {
      "@type": "Person",
      "name": "fredsiva",
      
    }, <--- highlights this as the error location
    "author": {
      "@type": "Person",
      "name": "fredsiva",
      
    },
```

Looking at `_layouts/post.html` I'm not sure how to fix it though - does it need re-generating in some way?

### PR DESCRIPTION
**Pull request by pljones**
**Short description of changes**

Fix JSON header layout

**Context: Fixes an issue? Related issues**
Fixes #1049

**Status of this Pull Request**
Need to see the Github build output...

**What is missing until this pull request can be merged?**
Might work, might not... let's see :)

**Does this need translation?**
No.

## Checklist
- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I'm sure that this Pull Request goes to the correct branch
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors.

### CODE REVIEW

**Comment by ann0see** [comment]
We could probably also merge this into release...

**Comment by pljones** [comment]
How about:
- merge anything from Weblate into next-release
- merge this into release
- rebase next-release to release
- update Weblate to pick up the above

**Comment by ann0see** [comment]
Possible, but this requires a review of weblate changes.

If we merge this to release, the setup should automatically merge (not rebase) release to next release.

**Comment by pljones** [comment]
OK, so
* [x] merge anything from Weblate into next-release (because I get nervous about it getting confused if it's got outstanding changes)
* [ ] merge this into release
* [ ] wait for the magic to happen
* [ ] assess any problems and fix them

**Review by ann0see — APPROVED** [review]

**Comment by ann0see** [comment]
Let's try this.

**Pull request merged**
