### PR TITLE
Add internal area (style and tone, administration,...)

### PR DESCRIPTION
**Pull request by ann0see**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

Merged all documents into one folder. They all don't need to be translated and are more of the meta documentation, contribution documents,... 

We should merge this soon and decide on the contents in an ongoing process. They're surely to be changed in future!

### CODE REVIEW

**Comment by gilgongo** [comment]
I recall a conversation about creating a new repo for this kind of thing, or was that different?

**Comment by ann0see** [comment]
Yes, it’s kind of related but see https://github.com/jamulussoftware/jamulus/issues/1764#issuecomment-853614959

**Comment by ann0see** [comment]
Can we merge this?

**Comment by gilgongo** [comment]
Don't see why not. We will be updating it later but it can be "version 1" for now.

**Pull request merged**
