### PR TITLE
typo in Installation for Android

### PR DESCRIPTION
**Pull request by jujudusud**
# Does this need translation?

- [ ] Yes 
- [x] No 

# Changes

In `Installation-for-Android.po` and `Installation-for-Android.md` fixing typo "pouvez -> puissiez" French grammar rule.

Fixing #1890

### CODE REVIEW

**Comment by ignotus666** [comment]
It looks good to me. Depending on the editor you use for the .po files it can change how the segments are wrapped in the 'msgid' and 'msgstr' fields, but it doesn't affect the end result. It also seems to have added a couple of lines of metadata but that doesn't matter either.

**Review by ignotus666 — APPROVED** [review]

**Comment by jujudusud** [comment]
> It looks good to me. Depending on the editor you use for the .po files it can change how the segments are wrapped in the 'msgid' and 'msgstr' fields, but it doesn't affect the end result. It also seems to have added a couple of lines of metadata but that doesn't matter either.

I'm using Linguist on Archlinux.

**Comment by ignotus666** [comment]
> I'm using Linguist on Archlinux.

Out of curiosity, did you run the po4a script or edit the .md file manually?

**Comment by jujudusud** [comment]
> 
> Out of curiosity, did you run the po4a script or edit the .md file manually?

After installing po4a 0.63 I used the script as you told me.
I only edit the .po file with linguist after rebasing to upstream/release branch.

**Pull request merged**
