### PR TITLE
Update DE translation for 3.8.0

### LINKED ISSUE #456: Update de web translation for 3.8.0
Hi @Helondeth, @ewarning,

We are getting ready for the 3.8.0 release and have created the [translate3_8_0](https://github.com/jamulussoftware/jamuluswebsite/tree/translate3_8_0) branch ([full diff](https://github.com/jamulussoftware/jamuluswebsite/compare/release..translate3_8_0)).

Because the English is still going through large changes, we are not expecting translations of anything other than the following pages:

- [Home page](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/1-index.html)
- [Setup](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Setup.md) (renamed from Getting-Started)
- Installation pages for each supported platform ([Windows](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Windows.md), [Mac](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Macintosh.md), [Linux](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Linux.md))

While you are of course welcome to translate more than this, please be aware that you may have to re-translate for the next release.

We would be happy if you updated the translations for **de** until **2021-05-15**.

Please

- Start your work in your fork on a branch based on jamuluswebsite's `translate3_8_0` branch.
- Update the language-specific files using your favorite editor (or directly on Github),
- Commit and push your changes to your fork,
- Open a Pull Request with your translations to the **translate3_8_0** branch with the subject `Update de web translation for 3.8.0`,
- Link your PR(s) to this issue by including `Fixes #456` in the PR content.

Note: The term "Central server" has been replaced with "Directory server"

This Issue is assigned to multiple people. Please coordinate who will translate what part.

Suggested commit and PR message:
```
Update de web translation for 3.8.0

Fixes #456
```

Feel free to use this Issue to discuss anything you need prior to making any PR (and in your native language if needed).

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/README.md#translating).

Thanks for contributing to Jamulus!

### PR DESCRIPTION
**Pull request by ewarning**
Update DE translation for 3.8.0

Fixes #456

### CODE REVIEW

**Comment by ignotus666** [comment]
I can't comment on the content because I don't know German, but I see that at the top of the 'Setup' document, 'permalink' is set as de/wiki/Setup - it should be just wiki/Setup, you don't need the 'de'. You also have the 'de' added in the 'Installation for Macintosh' file.

**Comment by ewarning** [comment]
@ignotus666 Okay, I’ll fix that, thanks for the hint.

**Comment by gilgongo** [comment]
For some reason, the Installation-for-Linux.md file seems to not be old version. The English for the next release is this one:

https://github.com/jamulussoftware/jamuluswebsite/blob/changes/wiki/en/en-Installation-for-Linux.md

Is that affecting all the languages?

**Comment by ewarning** [comment]
@gilgongo No, no I changed it on purpose, because I saw the folder structure like /wiki/de/de-files, I thought the links should follow that path. I already undid it.

**Pull request merged**
