### PR TITLE
DSCP Quality of Service Documentation

### PR DESCRIPTION
**Pull request by ghost**
# Does this need translation?

- [x] Yes 

- [ ] No 

# Changes

Added a new command line option (wiki/en/en-Command-Line-Options.md)
Added a new tip for Quality of Service (wiki/en/en-Tips-Tricks-More.md)

### CODE REVIEW

**Comment by gilgongo** [comment]
As a non-technical user, I'm trying to understand what I need to understand about  the -Q option. If I understand correctly, it implies that QoS is on by default at 128 ("To disable QoS use: --qos 0"), is that right? For other values, I should read an RFC, but what is the purpose of "Windows Quality of Service instructions"? Is it that I have to do this to get it to work on Windows? If so, do I need to do that on both client and server?

**Comment by ghost** [comment]
> As a non-technical user, I'm trying to understand what I need to understand about the -Q option. If I understand correctly, it implies that QoS is on by default at 128

Yes

> ("To disable QoS use: --qos 0"), is that right?

Yes

> For other values, I should read an RFC,

Yes

> but what is the purpose of "Windows Quality of Service instructions"? Is it that I have to do this to get it to work on Windows?

Yes. The procedure shown will work with any version of Jamulus on Windows..

> If so, do I need to do that on both client and server?

No. The Windows QoS policy applies to Jamulus.exe (Which I believe is a client or server depending on cli options).
Note that Windows uses DSCP values from 0 to 63 which uses 6-bits. The values passed by --qos are 4 times larger because 8 bits are represented. That is why the Windows instructions have you set DSCP to 32, whereas, --qos is 128

Note that -Q and --qos apply to both client and server as a General option.

**Comment by gilgongo** [comment]
@DavidSavinkoff  Thanks for the explanation. 

EDIT: just seen your https://github.com/jamulussoftware/jamulus/commit/377e6ec7e259332b856358520c5c4aff535d59a4#commitcomment-49361031 I'll look at that too.

So do I further understand that the Windows procedure is necessary in order to make the default value of 128 work? What happens to the default QoS in jamulus if I do not do the procedure?

Also, what is the effect on QoS if I set a different value on my client, and connect to a server that was running the default, and vice versa?

BTW I'm not asking for myself, but with a view to clarifying the documentation on this.

**Comment by ghost** [comment]
The 'Windows procedure' makes a new DSCP QoS policy for Jamulus.exe
The 'Windows procedure' will set the DSCP value in the IP header for any version of Jamulus. In other words; The 'Windows procedure' works regardless of the new code that I made because it blindly over-writes what my code does. My code may work on older Windows versions, or if MSFT changes Policy based QoS.
Note that the 'Windows procedure' is for newer Windows versions that have Policy based QoS.

> So do I further understand that the Windows procedure is necessary in order to make the default value of 128 work?

No. Newer Windows versions overwrite this 128 with whatever value you use in the 'Windows procedure'.

> What happens to the default QoS in jamulus if I do not do the procedure?

Newer Windows versions overwrite this 128 with 0.

> Also, what is the effect on QoS if I set a different value on my client, and connect to a server that was running the default, and vice versa?

On non-Windows, each client and server are fully independent and can have different --qos values. One is free to experiment here.
On Windows, the Policy based QoS is set for Jamulus.exe. Thus, the clients and servers will have the same DSCP value set by the 'Windows procedure'. This is completely OK.
It may be possible to: copy Jamulus.exe Jamuluserver.exe and make a QoS Policy (Windows procedure) for each of Jamulus.exe and Jamuluserver.exe
Note that you may need to go through the 'Windows procedure' every time Jamulus is updated.
I believe that, over time, Windows users will come up with ideas on QoS policies which are better than what I'm suggesting.

**Comment by gene96817** [comment]
What happens if some users are on Macs? Does this scheme require the server and all clients to be Windows-based?

**Comment by gilgongo** [comment]
@gene96817 Macs use the Jamulus QoS OK as far as I understand - it's only Windows that will ignore it unless you reconfigure it not to do so. As to your second question, as stated above, "On non-Windows, each client and server are fully independent and can have different --qos values."

**Comment by gilgongo** [comment]
@DavidSavinkoff  Now that I undertand more about QoS and the use of `-Q` on Jamulus, would it be OK if I re-wrote the help the website on it to read:

> Sets the quality of service DSCP value. Default is 128. Disable with 0.  Note: This option is ignored by Windows, but see [Tips & Tricks](Tips-Tricks-More#quality-of-service) for how to apply it.

And the Tips & Tricks preamble to read:

### Quality of Service

Jamulus uses DSCP/CS4 opportunistically to deal with buffer bloat, and uses a default DSCP/CS4 value of 128 (or 0x80). This is compatible with IPv4 and IPv6. Other values can be set using the `-Q` option, eg  `-Q [0..255]` (where 0 disables QoS). If you want to explore the effect of non-default settings, see [RFC4594](https://tools.ietf.org/html/rfc4594). However, most people will have no need to do this.

#### Using Quality of Service on Windows

Jamulus’s QoS settings (including the default) have no effect on Windows because the operating system ignores them. To enable Quality of Service for Jamulus, you must follow these instructions. Note also that you may need to repeat this procedure every time Jamulus is updated.

\[instructions for Windows\]

**Comment by ghost** [comment]
> What happens if some users are on Macs?

DSCP Quality of Service is compatible with all Jamulus versions across all platforms.
I'm expecting that Macs will be identical to Linux in behaviour.

> Does this scheme require the server and all clients to be Windows-based?

No.

The 'Windows procedure' is an instruction for Windows users to make a QoS policy for Jamulus. If they don't, then their Jamulus-3.7.1 will operate with the same DSCP Quality of Service as Jamulus-3.7.0 did.
BTW if you do the 'Windows procedure' on your current Jamulus, you will get DSCP/CS4 in the IP header octet right now.

**Comment by ghost** [comment]
> @DavidSavinkoff Now that I undertand more about QoS and the use of `-Q` on Jamulus, would it be OK if I re-wrote the help the website on it to read:
> 
> > Sets the quality of service DSCP value. Default is 128. Disable with 0.  Note: This option is ignored by Windows, but see [Tips & Tricks](Tips-Tricks-More#quality-of-service) for how to apply it.
> 
> And the Tips & Tricks preamble to read:
> ### Quality of Service
> 
> Jamulus uses DSCP/CS4 opportunistically to deal with buffer bloat, and uses a default DSCP/CS4 value of 128 (or 0x80). This is compatible with IPv4 and IPv6. Other values can be set using the `-Q` option, eg `-Q [0..255]` (where 0 disables QoS). If you want to explore the effect of non-default settings, see [RFC4594](https://tools.ietf.org/html/rfc4594). However, most people will have no need to do this.
> #### Using Quality of Service on Windows
> 
> Jamulus’s QoS settings (including the default) have no effect on Windows because the operating system ignores them. To enable Quality of Service for Jamulus, you must follow these instructions. Note also that you may need to repeat this procedure every time Jamulus is updated.
> 
> [instructions for Windows]

This looks very good. I read it like a lawyer. IANAL

**Pull request merged**
