### PR TITLE
Next-release 3.10 nl images

### LINKED ISSUE #956: [Translate] Adding NL images for 310 to repo
This issue is to generate user content image for the 3.10 website.

My Profile settings:
settings-profile-310-nl

Audio/Network settings:
settings-network-310-nl

Advanced settings:
settings-advanced-310-nl

### PR DESCRIPTION
**Pull request by henkdegroot**
**Short description of changes**
Updating INC files to point to new NL screenshots for v3.10

**Context: Fixes an issue? Related issues**

Fixes: #956 

**Status of this Pull Request**

Completed

**What is missing until this pull request can be merged?**

Nothing

**Does this need translation?**

No

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

### CODE REVIEW

**Comment by henkdegroot** [comment]
Can someone confirm the Server Setup and Options images are no longer used and I should remove them from the PR?

EDIT: I discovered they have been removed indeed, so will remove them here.

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
Must be merged AFTER the Weblate PR and only if Weblate is clean.

**Comment by ignotus666** [comment]
This won't affect Weblate - it's changes to translatable docs we have to be careful with.

**Comment by pljones** [comment]
@ignotus666 if this is okay to merge to next-release, please do so.

**Pull request merged**
