### PR TITLE
Update Index IT

### PR DESCRIPTION
**Pull request by dzpex**
---
name: Changes on Index of IT
about: I
labels: ""
assignees: ''
---
# Does this need translation

- [] Yes 
- [x] No 

# Changes

### CODE REVIEW

**Comment by dzpex** [comment]
I hope all is ok...

**Review by gilgongo — APPROVED** [review]
Looks OK to me!

**Comment by ann0see** [comment]
It includes parts of the changes branch ;-(. Can you select the release branch and copy your changes there before opening the pull request? This is a button at the top left in the code tab.

**Comment by gilgongo** [comment]
Oops. Shall I revert that?

**Comment by ann0see** [comment]
Maybe we should put the Release branch as default branch?

**Comment by gilgongo** [comment]
I'd forgotten that it wasn't.

**Comment by ann0see** [comment]
Ok. Just did this.

**Comment by ann0see** [comment]
@dzpex could you please open a new PR directly to release (edit the file on the release branch which is now the default one?)

**Pull request merged**
