### PR TITLE
Sync release to changes

### PR DESCRIPTION
**Pull request by ann0see**
#558 was merged and resulted in conflicts. Since the po4a scripts were run (on release and next-release), .po files are at different stages and the conflicts need to be resolved.

This PR should fix https://github.com/jamulussoftware/jamuluswebsite/actions/runs/1030148493 which failed due to conflicts.

### CODE REVIEW

**Comment by ann0see** [comment]
@ignotus666 not 100% sure here. We need to resolve conflicts in .po files... Can they be re-generated somehow? Some changes are obvious, while others aren't.

**Comment by ignotus666** [comment]
I think the problem is this: in #560 the .po files were updated against newer EN .md docs and some were deleted (which is why e.g. this PR wants to re-create "command-line-options" for ES, but then delete it). This PR is trying to update some docs and at the same time "downgrade" them... My grasp of all this is very tenuous. Can the .po files be excluded from this sync PR, and do those changes in  #558 in 'next-release'? Would a future next-release -> release merge work if we did that?

**Comment by ignotus666** [comment]
> Can they be re-generated somehow?

It's possible, but not without _**a lot**_ of work. Those files hold the source-target segment pairings. If they disappear, so do the pairings. I have translation memories for nearly all of them, but it would mean having to revise every single translated doc again as there have been multiple corrections since I saved those memories. So... best avoided.

**Comment by ann0see** [comment]
Ok. Just went through the files. Except for */Server-Linux.po all files are quite obvious.
```
#. type: Plain text
<<<<<<< HEAD:translator-files/po/pt/Server-Linux.po
#: wiki/en/Server-Linux.md:79
#, no-wrap
msgid "**Note:** You will need to save recordings to a path _outside_ of the jamulus home directory, or remove `ProtectHome=true` from your systemd unit file (be aware that doing so is however a potential security risk).\n"
=======
#: wiki/en/Server-Linux.md:51
msgid "`journalctl -u jamulus-headless`"
>>>>>>> origin/release:_translator-files/po/pt/Server-Linux.po
msgstr ""
```
And 
```
#. type: Plain text
<<<<<<< HEAD:translator-files/po/pt/Server-Linux.po
#: wiki/en/Server-Linux.md:86
#, no-wrap
msgid ""
"~~~\n"
" [Unit]\n"
" Description=Toggle recording state of Jamulus server\n"
" Requisite=Jamulus-Server\n"
=======
#: wiki/en/Server-Linux.md:55
msgid "`journalctl -u jamulus-headless --since today`"
>>>>>>> origin/release:_translator-files/po/pt/Server-Linux.po
msgstr ""
```
And 
```
#. type: Plain text
<<<<<<< HEAD:translator-files/po/pt/Server-Linux.po
#: wiki/en/Server-Linux.md:93
msgid "For starting a new recording:"
=======
#: wiki/en/Server-Linux.md:59
msgid "`journalctl -u jamulus-headless --since \"1 hour ago\"`"
>>>>>>> origin/release:_translator-files/po/pt/Server-Linux.po
msgstr ""
```
And 
```
#. type: Plain text
<<<<<<< HEAD:translator-files/po/pt/Server-Linux.po
#: wiki/en/Server-Linux.md:103
#, no-wrap
msgid ""
" [Service]\n"
" Type=oneshot\n"
" ExecStart=/bin/systemctl kill -s SIGUSR1 Jamulus-Server\n"
"~~~\n"
=======
#: wiki/en/Server-Linux.md:63
msgid "`journalctl -u jamulus-headless | grep connected`"
>>>>>>> origin/release:_translator-files/po/pt/Server-Linux.po
msgstr ""
```
And 
```
#. type: Plain text
<<<<<<< HEAD:translator-files/po/pt/Server-Linux.po
#: wiki/en/Server-Linux.md:107
msgid "Run `sudo systemctl daemon-reload` to register them for first use."
=======
#: wiki/en/Server-Linux.md:67
msgid "`journalctl -f -u jamulus-headless`"
>>>>>>> origin/release:_translator-files/po/pt/Server-Linux.po
msgstr ""
```
are strange.

**Comment by ignotus666** [comment]
> are strange.

Why?

**Comment by ignotus666** [comment]
A possibility could be to take the .po files from 'release' and merge them into 'next-release' via a branch. That would revert them to their state before they were updated to include the changes from the new EN -md documents. The next time 'update-templates' is run they'll get those changes back in anyway.

**Comment by ann0see** [comment]
Yes. That’s an option.

**Comment by ann0see** [comment]
Closing. See #570

**Pull request closed without merging**
